### ISSUE TITLE
záhlaví ročníků a čísel u periodik

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#100]
U ročníků zobrazovat v záhlaví ne číslo ročníku, ale název periodika a rok vydání.
U čísel zobrazit název periodika a datum vydání, pokud není datum vydání tak rok vydání a číslo.

**Comment by ovyhlidal** [comment]
Opraveno. Bude k testovani v dalsim releasu.

**Comment by zabak** [comment]
funguje
