### ISSUE TITLE
Info o aplikaci přesunout do systémových nastavení

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#101]
Neměla by být součástí aplikace ale měla by být podobně jako u jiných aplikací dostupná skrze nastavení iOSu.

**Comment by ovyhlidal** [comment]
Toto je podle me nevhodne. Soucasti systemovych nastaveni jednotlivych aplikaci jsou polozky, ktere ovlivnuji chod aplikace a ne informace o aplikaci jako takove. Jsou tam napriklad nastaveni zda ma aplikace prava na kameru, internetove pripojeni skrze data a podobne.

**Comment by zabak** [comment]
Třeba Testflight v nastavení zobrazuje verzi, twitter obsahuje link na "více informací o twitteru", ibooks obsahuje položku "uznání", Safari nějaké odkazytypu Safari a soukromí. Ale netrvám na tom.
