### ISSUE TITLE
Ukazovat číslo stránky při používáni posuvniku

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#102]
Podobně jako u ibooks

**Comment by black23** [comment]
Obecne bych se v rozhrani u iBooks inspiroval. Maji to celkem dobre vymyslene.

![img_2712](https://cloud.githubusercontent.com/assets/5516936/15604859/c9c568ae-2402-11e6-8b22-f61af303c7de.PNG)

**Comment by ovyhlidal** [comment]
Pridano do nove verze pro testovani 1.2.0. Zaviram toto issue.
