### ISSUE TITLE
Pád aplikace při psaní dotazu

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#103]
Napíšu Lid a aplikace spadne.
Napíšu Obnova a dám hledat a aplikace spadne a pak když ju spustím znova tak už jde rovnou do pádu. Takže teď mi na daném stroji nefunguje.

**Comment by ovyhlidal** [comment]
Pracuji na oprave. Vsimnul jsem si toho az kdyz jsem nahral tuto verzi na realne zarizeni. Na simulatoru se aplikace chovala naprosto jinak :/

**Comment by ovyhlidal** [comment]
Opraveno. Odpoledne uploadnu dalsi verzi spolecne s opravou dalsich chyb.

**Comment by ovyhlidal** [comment]
V soucasne verzi je to ok, na zarizeni mi to nepada. Muzete udelat retest a pripadne zavrit toto issue? Diky

**Comment by zabak** [comment]
vyřešeno, už to nepadá
