### ISSUE TITLE
Hledání - historie vs. našeptávač

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#104]
Pokud začnu psát, neměly by se mi nabízet irelevantní termíny z historie hledání - aplikace si zřejmě pamatuje 3 poslední a nabízí mi je na prvních místech nezávisle na tom, že jsem začal psát něco úplně jiného. Historii hledání si systém může pamatovat i delší než 3 poslední dotazy, ale podstatnější je relevantní našeptávání. To by mělo být i rozumně řazeno, pokud začnu psát "Davidova" tak po napsání "Da" se mi zobrazí první titul začínající na Da až na 3. místě a další až na 10.

**Comment by ovyhlidal** [comment]
Historii hledani jeste opravim. Pro zobrazeni vysledku z historie hledani jsou vyhrazeny prvni 3 mista ve vysledcich. Ostatni mista jsou v takovej poradi, v jakem je dostanu od serveru. Jejich poradi v naseptavaci nijak nemenim.

**Comment by ovyhlidal** [comment]
Upravim filtr relevantnich vysledku z historie.

**Comment by ovyhlidal** [comment]
@zabak  pri zmene krameria se ma aktualni historie smazat? Tzn. pri vyhledavani v jinem krameriu se nebudou zobrazovat predchozi hledani.

**Comment by zabak** [comment]
Ne, uživatel možná hledal něco co v jednom Krameriu nenašel, tak šel pak do dalšího a chce hledat to samé.

**Comment by ovyhlidal** [comment]
Ok, diky za vyjasneni :)

**Comment by honza-rychtar** [comment]
@ovyhlidal ukladej si jen unikatni vysledky. Kdyz kliknu 3x na Lidove noviny. Tak mam v naseptavaci 3x pod sebou Lidove noviny.

**Comment by ovyhlidal** [comment]
Opravil jsem filtrovani naposled hledanych. Odstranil mazani historie v pripade, ze se zmeni kramerius. Filtruje se na zaklade predikatu "beginsWith" takze se vysledky v lokalni historii zobrazuji presne podle toho, co uzivatel zadava. Poupravil jsem chovani naseptavace. Uploadnu verzi na testovani a budu pokracovat dal v upravach.

**Comment by zabak** [comment]
vyřešeno
