### ISSUE TITLE
Hledání - nefunguje

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#105]
Začnu psát Davidova houpačka, našeptávač něco nabídne, vyberu "Davidova houpačka", systém zahlásí červenou hlášku nenalezeno.

**Comment by ovyhlidal** [comment]
Opravil jsem problem s vyhledavacem. Bude k otestovani v dalsi verzi

**Comment by zabak** [comment]
otestováno, funguje
