### ISSUE TITLE
Nastavení - nevypínat obrazovku

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/kramerius-for-ios#106]
Nikde jsem nenašel možnost nastavit, aby se display po čase neztlumil a nasledne nevypnul/zamknul.

**Comment by ovyhlidal** [comment]
Pokud je toto pozadavek, tak neni problem ho do nastaveni aplikace pridat. Jaka bude vychozi nastaveni? Vypnuto/Zapnuto?

**Comment by jandera** [comment]
Myslím, že by se to hodilo, při testování jsem se začetl do složitějšího textu a než jsem došel na konec stránky tak mi display ztmavl. Aplikace Kramerius pro Android toto nastavení má a je defaultně nastaveno nevypínat/ztmavovat obrazovku při prohlížení dokumentu.

**Comment by zabak** [comment]
Myslím, že není nutné, aby se obrazovka nevypnula vůbec, spíš aby se vypla až za dobu, jakou se čte stránka knihy - například místo 2 minut počkat 10 nebo 15 minut. Jde o to, aby někdo v dobré víře neodložil tablet a on by se mu za pár hodin úplně vybil.

**Comment by ovyhlidal** [comment]
Osobne si myslim, ze bych musel udelat neco, co bude sledovat uzivatele, jak dlouho si cte knizky a podle toho potom odhadovat jak dlouho by takovou stranku mohl cist. Ja bych to idelane udelal tak, ze pokud uzivatel vejde do knizky a bude aktivne cist, tak se mu display nezhasne. V okamziku kdy nebude zadna uzivatelska interakce po dobu napr 5minut, tak povolim zhasnuti displaye a uspani aplikace.

**Comment by honza-rychtar** [comment]
Ja bych to nekomplikoval. Kdyz nevypinat, tak nevypinat vubec. Kdyz vypinat, tak podle systemoveho nastaveni.
Ja mam treba v telefonu automaticke vypinani az po 20 minutach ... z timto pristupem by pro me nevypinat vlastne znamenalo, ze se vypne driv ...

**Comment by zabak** [comment]
ios má volby 2,5,10,15, Nikdy. Dokáže iOS aplikaci říct, jak dlouho už uživatel neprovedl žádnou interakci? Jakým způsobem se aplikace dozví, že chce iOS vyplnout obrazovku, musí se ptát, nebo jí to systém řekne, nebo nijak? A jaké má aplikace možnosti to zakázat? Musí to nastavit, nebo se jí systém ptá?

**Comment by ovyhlidal** [comment]
System aplikaci nedokaze rict, jak dlouho uzivatel neprovedl zadnou akci. Toto chovani se musi naprogramovat. V aplikaci muzu jen rict, zda se ma systemove nastaveni zhasinani displaye ignovat nebo ne. 
Existuji privatni API, ale pokud bychom je pouzili tak bysme porusili Apple guidelines a za takove chovani muzou aplikaci vyhodit z appstoru, takze to urcite neni dobra cesta.

**Comment by zabak** [comment]
V tom případě bych šel cestou kterou psal Honza. Přepínač v nastavení - nevypínat obrazovku. Ten by se aplikoval jen když je člověk v prohlížení stránky, pokud jsem v hledání, nastavení, přehrávání zvuku apod. tak ne.

**Comment by ovyhlidal** [comment]
Ok souhlasim.

**Comment by ovyhlidal** [comment]
V dalsim buildu verze 1.1.2 bude pripraveno na testovani.

**Comment by zabak** [comment]
vyřešeno
