### ISSUE TITLE
Hláška místo pádu aplikace: neexistence dokumentu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#108]
Pokud zůstane aplikace zapnutá a v DK dojde k nějakým změnám (odstranění konkrétního UUID) aplikace spadne. Místoho by měla zahlásít, že nemůže najít dokument a nabídnout nějaké řešení, například načtení výchozích dokumentů.

**Comment by zabak** [comment]
Až bude toto potřeba testovat, domluvíme se na konkrétním dokumentu, na kterém se to otestuje.

**Comment by honza-rychtar** [comment]
K tomu nemusime vytvaret testovaci dokument, ktery nasledne z Krameria smazeme.
Tohle si muze Ondra lehce opravit a otestovat u sebe ve vyvojove verzi, kdyz si pri otevreni dokumentu umele zmeni uuid na nejaky nesmyslny retezec.

**Comment by ovyhlidal** [comment]
Kramerius mi posle JSON se status a message. @honza-rychtar zobrazujes text z message uzivateli, nebo na to pouzivas nejakou obecnou hlasku? 
Diky

**Comment by zabak** [comment]
Zavírám, kdyby se vyskytl problém, znovu se otevře nebo založí nové issue.
