### ISSUE TITLE
Výsledky hledání - veřejný dokument nelze otevřít

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/kramerius-for-ios#109]
Ve výsledcích dotazu nelze otevřít žádný dokument, u všech se objeví hláška, že není veřejně přístupný, přesto, že je.

**Comment by ovyhlidal** [comment]
Opravil jsem chybu v parsovani dostupnosti vysledku, ktera branila otevreni dokumentu. Bude pripraveno k testovani behem odpoledne.
