### ISSUE TITLE
V tabu nejnovejsi zobrazovat jen verejne dokumenty

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#110]
Zejmena kdyz neverejne dokumenty aplikace nedovoli vubec otevrit.

**Comment by ovyhlidal** [comment]
Tzn pri requestu na nejnovejsi uplne ignorovat to, co si uzivatel muze nastavit v nastaveni? 
@zabak 
Pokud je to tak, provedu zmenu.

**Comment by zabak** [comment]
zatím má toto řešení logiku, souhlasím.

**Comment by ovyhlidal** [comment]
Opraveno, bude pripraveno k otestovani v dalsi verzi 1.1.3 build 4.
