### ISSUE TITLE
Aplikace si nepamatuje pozice zalozek

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#112]
Pokud si preskladam spodni zalozky a vypnu aplikaci, tak pri dalsim spusteni jsou zalozky zase ve vychozim poradi.

**Comment by ovyhlidal** [comment]
Povolit uzivateli menit pozice tabu jsem nemel puvodne ani v planu, jen jsem tu moznost zapomel vypnout.

**Comment by ovyhlidal** [comment]
Opraveno - zakazal jsem uzivateli menit poradi tabu. K testovani ve verzi 1.1.3(2)
