### ISSUE TITLE
Našeptávač - odstranit hlášku nenalezeno - je matoucí

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#116]
Napíšu Lidove a objeví se hláška že nebylo nic nalezeno - ale to není pravda, protože když dám hledat, tak se něco najde. Uživatel může ale tou hláškou být odrazen od toho aby zmáčkl tlačítko hledat.

**Comment by black23** [comment]
Strejne chovani i v pripade, ze vyberu i naseptany nazev. To je matouci jeste vic.

**Comment by ovyhlidal** [comment]
Odstranil jsem hlasku, ktera se zobrazovala v pripade, ze naseptavac vratil 0 vyskytu. Hlaska, ktera se zobrazi po vybrani naseptaneho nazvu byla zpusobena tim, ze requesty naseptavace nerespektovali nastaveni zobrazeni jen verejnych del. Tim padem uzivateli mohlo byt naseptano neco co je neverejne a kdyz pak chtel vyhledat tento titul, tak nedostal zadne vysledky.
