### ISSUE TITLE
Historie neukládá všechno

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#117]
Hledal jsem Lidové bobi, Lidobe, Lidoii a Lidové. Lidové se do historie hledání neukládá. Pak jsem zadával jiné dotazy nezačínající na lid a pak se ta historie vzpamatovala a ty starší promazala. Ale zase se mi do ní neukládá jiný hledaný termín a ty staré termíny se tam pořád drží.

**Comment by ovyhlidal** [comment]
Do historie ukladam hledani v okamziku, kdy uzivatel klikne na naseptany termin nebo klikne na hledat. Neukladam pokud jen neco napise do vyhledavaciho pole.
