### ISSUE TITLE
1.1.2 (8) padá při pokusu hledat

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#118]
Při pokusu napsat více, jak jedno písmeno do pole pro hledání appka spadne.

**Comment by ovyhlidal** [comment]
Je to posledni testovaci build cislo 8? Predchozi verze s tim mela problem.

**Comment by black23** [comment]
Verze z 04/09/2016

**Comment by ovyhlidal** [comment]
Uz se mi to podarilo reprodukovat, jeste dnes to bude opraveno. Vypada to, ze pri updatu verze se spatne odstranila nekompatibilni data z predchozi verze.

**Comment by ovyhlidal** [comment]
Opraveno ve verzi 1.1.2 (9)

**Comment by black23** [comment]
potvrzuji a zaviram
