### ISSUE TITLE
Archiválie nejdou otevřít

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#119]
Např. hledat Miscellanea najde 5 dokumentů typu archiválie - ani jeden nejde otevřít - nic se nestane - ani se nezobrazí žádná hláška, dokumenty jsou přitom volné.

**Comment by ovyhlidal** [comment]
To bude pravdepodobne tim, ze aplikace nezna archivalie a nevi jak je otevrit. Podivam se na to.

**Comment by zabak** [comment]
Podobně se chovají přílohy k periodikům, konkrétně třeba Brünner Zeitung, ročník 1883, kde je na začátku řada příloh označených jako neznámý typ. Mělo by se to chovat takto: http://www.digitalniknihovna.cz/mzk/periodical/uuid:cf2e7320-22cf-11e4-8413-5ef3fc9ae867

**Comment by honza-rychtar** [comment]
Aplikace by mela znat tyto typy:
    "model" : {
        "monograph" : "Kniha",
        "periodical" : "Noviny a časopisy",
        "map" : "Mapa",
        "sheetmusic" : "Hudebniny",
        "graphic" : "Grafika",
        "archive" : "Archiválie",
        "soundrecording" : "Zvukové nahrávky",
        "periodicalvolume" : "Ročník periodika",
        "periodicalitem" : "Číslo periodika",
        "manuscript" : "Rukopis",
        "page" : "Stránka",
        "supplement" : "Příloha",
        "article" : "Článek",
        "internalpart" : "Vnitřní část",
        "soundunit" : "Album",
        "track" : "Nahrávka"
    }

Dalsi vec je razeni. Tady jsem u weboveho klienta obesel API Krameria a seznam potomku periodika a rocniku periodika beru pres Solr, coz nakonec vede k lepsimu serazeni, zejmena pokud je to kombinovane s prilohami.

**Comment by ovyhlidal** [comment]
Diky @honza-rychtar  Kdyz jsem se koukal kdysi davno nekam do dokumentace, tak tam takovej vycet urcite nebyl. Doplnim. Diky

**Comment by honza-rychtar** [comment]
Mam lokalizacni soubory pro vsechny typy dokumentu, typy stran, jazyky, autorske role a knihovny v cestine, slovenstine, anglictine a nemcine.
Z toho jednak zjistis vsechny mozne kody pro ruzne pole a zaroven budes mit preklady.
Pouziju to i v Androdi aplikaci (vetsina uz tam v anglictine a cestine je) a tobe to muzu dat taky.

**Comment by ovyhlidal** [comment]
Pokud je mas a jsi ochotny je poslat, tak by to bylo super :) Diky moc :)

**Comment by ovyhlidal** [comment]
Opraveno, pridany vsechny typy, ktere aplikace nepodporovala. K testovani bude v dalsim releasu 1.1.3 (2).
