### ISSUE TITLE
Ceske nazvy 

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#12]
Pridat ceske nazvy k ruznym druhum dokumentu - aktualne se pouziva to, co prijde - soundunit, monograph etc...

**Comment by ovyhlidal** [comment]
@zabak 
Mame nejakou mnozinu ceskych prekladu pro vsechny mozne druhy dokumentu?

**Comment by zabak** [comment]
Buď převzít z Androidu, nebo Krameria. @honza-rychtar odkud jsi to bral ty Honzo?

**Comment by honza-rychtar** [comment]
Pouzivam jine nazvy nez K4 klientovi (Monografie -> Kniha, ...)
Ceske nazvy tady nahore:
https://github.com/moravianlibrary/kramerius-for-android/blob/master/app/src/main/res/values-cs/strings.xml
Anglicke:
https://github.com/moravianlibrary/kramerius-for-android/blob/master/app/src/main/res/values/strings.xml

**Comment by honza-rychtar** [comment]
Jeste je v metadatech potreba prelozit kody na cs/en nazvy u:
1) sigla instituce -> nazev instituce
2) kod jazyka -> nazev jazyka
3 ) kod role (u autora) -> nazev role

Mam to mapovani ulozene v databzi, tady jsou insert skripty:
ad 1) https://github.com/moravianlibrary/kramerius-for-android/blob/master/app/src/main/res/raw/institution.sql
ad 2) https://github.com/moravianlibrary/kramerius-for-android/blob/master/app/src/main/res/raw/languages.sql
ad 3) https://github.com/moravianlibrary/kramerius-for-android/blob/master/app/src/main/res/raw/relators.sql

**Comment by ovyhlidal** [comment]
@honza-rychtar @zabak Diky, jeste dnes opravim.

**Comment by ovyhlidal** [comment]
Opraveno. Bude v 1.0.7.
