### ISSUE TITLE
Nejnovější dokumenty: dokumenty jiné knihovny

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#123]
Verze Verze 1.1.3 (1): MKCT, při zobrazení nejnovějších tam jsou dokumenty úplně jiné knihovny.
![img_3346](https://cloud.githubusercontent.com/assets/5516936/18586406/b874ace6-7c1c-11e6-8219-0243b2a3bcbc.PNG)

**Comment by black23** [comment]
Doplnění. Vypadá to, že tam zůstanou je při přecházení z jedné knihivny do druhé. Když jsem schodil appku a zkusil t znu již je ok. Cache?

**Comment by ovyhlidal** [comment]
Jo jednalo se o cache - collection view se sefreshnulo, ale melo stara data... Bude pripraveno na otestovani v dalsim buildu. 1.1.3(2)

**Comment by black23** [comment]
Super, otestuji a případně pak zavřu.

**Comment by zabak** [comment]
Nepodařilo se mi reprodukovat, takže předpokládám, že je vyřešeno a zavírám.
