### ISSUE TITLE
hlavní obrazovka - na ipadu se zobrazuje o sloupec méně než je místa

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#124]
V portrait režimu jen 1 loupec místo dvou, v landscape 2 sloupce místo 3. Na ipadu i ipadu mini.

**Comment by ovyhlidal** [comment]
Na ipadu mini 2 je i spatne zarovnani horni listy.

**Comment by ovyhlidal** [comment]
Opraveno a testovano na iphonu 6, 6plus i ipadu mini2.
