### ISSUE TITLE
chybi moznost kliknout na informace o nahravce 

### ISSUE THREAD

**Issue by filipsir** [moravianlibrary/kramerius-for-ios#128]
myslim si, ze asi toto chybi i u dalsich vecech tedy dokumentech. proc neni mozne mit ikonku i a pri kliknuti na ni to zobrazi bibliograficky zaznam. u zvukove nahravky velmi potrebne

**Comment by ovyhlidal** [comment]
Pridam.

**Comment by ovyhlidal** [comment]
Pridana moznost zobrazit zakladni sadu informaci. Postupne se budou zobrazovane informace rozsirovat. K otestovani bude v dalsi verzi.
