### ISSUE TITLE
text okénka Nelze pokračovat

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#129]
Když vyskočí okénkoo Nelze pokračovat Zkontrolujte své připojení a jsou tam tlačítka Ano a Zrušit, tak nevím co mám dělat, co se sane když zmáčknu jedno nebo druhé. Je v tom rozdíl?

**Comment by ovyhlidal** [comment]
Je pravda, ze v tomto pripade by pravdepodobne bylo lepsi pouzit jen jedno tlacitko. Pokud je to v popup okne, tak to az tak nevadi, postupne predelavam vsechny hlasky na novy zpusob prezentovani hlasek - pomoci barevnych list vysouvacich z horni casti obrazovky. Kazdopadne by bylo dobre vyresit jaka tlacitka by tato hlaska mela ci nemela mit.

**Comment by zabak** [comment]
V tomto případě bude záležet na textu. Klidně tam může být OK, nebo i nic- že se to jen na chvíli ukáže. Měl jsem při testování problém, že wifi dost často vypadávala, i když byl signál třeba dvě čárky. Že se prostě po zadání dotazu nic nedělo. Pak se to ale nějak chytlo a něco se stalo. Ale někdy bylo třeba to hledání zadat několikrát. Možná ale, že za tím byly výpadky našeho Krameria - tohle v aplikaci asi nepoznám, jestli se nespojila kvůli slabému signálu wifi, nebo kvůli tomu, že spadl Kramerius, že?

**Comment by ovyhlidal** [comment]
Pridal jsem podporu toho, ze aplikace pozna, jestli ma uzivatel pripojeni k internetu ci nema... Postupne nahrazuji stare hlasky novym systemem hlasek. Cele reseni bude k otestovani v dalsi verzi.

**Comment by zabak** [comment]
Nevím jestli to patří sem nebo do nového bugu, ale řekněme že sem. Když jsem například na stránce se zajímavými knihami a vypnu wifi, tak  když tapnu na nějaký dokument, tak sice vyjede červená chybvá hláška, ale hned je překryta prázdnou stránkou se slovem Zpět

**Comment by zabak** [comment]
To s tím vypnutím wifi by se ještě dalo vylepšit, ale jde o speciální případ, takže zavírám.
