### ISSUE TITLE
Listování ve svazku

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/kramerius-for-ios#13]
•	U vetsiny dokumentu se po kliku na titul nezobrazi zadna prvni strana nebo obalka
•	Nekdy zafunguje ikona knihy vlevo dole
•	Listovani tahanim soupatka je moc hrube, clovek se netrefi tam, kam chce (a pro posun na dalsi stranku je to uplne nepouzitelne)
•	default velikost stranky je mala (mozna optimalizovana pro telefon?)
•	Prechod na dalsi stranku: pohyb prstem od boku do stredu displeje (tj. nativne dle papirove knihy) neprejde na dalsi stranku, ale posune stavajici po displeji
•	Tap na okraj stranky nekdy funguje, ale vetsinou ne (spis zafunguje jako schovani/zobrazeni horni a dolni listy)
•	Nekdy funguje dvoj-tap, ale ten zas otoci dve stran
•	Nekdy appka pri listovani spadne
•	Po kliku na ikonu knihy se zobrazi nahledy stranek vsechny s cislem 0
•	Po kliku na stranku se casto zobrazi stranka "roztristena"
![img_3793](https://cloud.githubusercontent.com/assets/16186956/11622576/268b2042-9cc7-11e5-8feb-d2c5a5af536a.PNG)
![img_3794](https://cloud.githubusercontent.com/assets/16186956/11622577/30459752-9cc7-11e5-8166-307ce98e16a8.PNG)
![img_3797](https://cloud.githubusercontent.com/assets/16186956/11622579/3611b0a8-9cc7-11e5-9e9f-edfef2085a37.PNG)

**Comment by ovyhlidal** [comment]
• Listovani tahanim soupatka je moc hrube, clovek se netrefi tam, kam chce (a pro posun na dalsi stranku je to uplne nepouzitelne) - posuvnik se nastavuje podle poctu stran - pokud ma nejaky titul hodne stranek, tak je posuvnik nepouzitelny. 

• default velikost stranky je mala (mozna optimalizovana pro telefon?) - zkusim udelat nejake optimalice

• Prechod na dalsi stranku: pohyb prstem od boku do stredu displeje (tj. nativne dle papirove knihy) neprejde na dalsi stranku, ale posune stavajici po displeji  - v soucasne verzi to nejde ani jinak udelat, jedna se o limitace prohlicky
 
• Tap na okraj stranky nekdy funguje, ale vetsinou ne (spis zafunguje jako schovani/zobrazeni horni a dolni listy) - zvetsim dotykove zony na krajich a tim by se tomuto melo predejit

• Nekdy funguje dvoj-tap, ale ten zas otoci dve stran - dvoj tap 2x klikne na otoceni stranky, proto se stranka otoci 2x. 

• Nekdy appka pri listovani spadne - opraveno

• Po kliku na ikonu knihy se zobrazi nahledy stranek vsechny s cislem 0 - bude opraveno

• Po kliku na stranku se casto zobrazi stranka "roztristena" - pravdepodobne nejaky problem ve ctecte, zkusim se podivat proc se to deje

**Comment by honza-rychtar** [comment]
> Listovani tahanim soupatka je moc hrube, clovek se netrefi tam, kam chce (a pro posun na dalsi stranku je to uplne nepouzitelne) - posuvnik se nastavuje podle poctu stran - pokud ma nejaky titul hodne stranek, tak je posuvnik nepouzitelny.

Soupatko nema slouzit k prechodu na predchozi/dalsi stranku - to u vicestrankovych dokumentu proste fungovat nebude. Slouzi jako info o aktualni pozici v dokumentu a k prechodu o velke useky, napr. nalistovani na konec dokumentu.

> Nekdy funguje dvoj-tap, ale ten zas otoci dve stran - dvoj tap 2x klikne na otoceni stranky, proto se stranka otoci 2x.

Pokud je dvoj-tap matouci (ja bych treba cekal zoom), tak by bylo dobre nastavit nejaky threshold (napr. 500 milisekund), kdy se po tapu dalsi tap ignoruje.

> Prechod na dalsi stranku: pohyb prstem od boku do stredu displeje (tj. nativne dle papirove knihy) neprejde na dalsi stranku, ale posune stavajici po displeji - v soucasne verzi to nejde ani jinak udelat, jedna se o limitace prohlicky

Nevim jak to funguje na iOS, ale urcite je tam nejaka view hierarchy a callback propagation, kdy v konteineru, ktery obsahuje prohlizecku, muzu zachytavat gesta a pokud simuluji swipe (tah zleva do prava), tak zastavit propagaci gesta do prohlizecky a interpretovat to tak, ze otocim stranku.
Na Androidu taky v prvnich verzich nebyla podpora swipe, takze to neni tak nutne, zejmena pokud se bude prohlizecka prepisovat za nativni. Nicmene, otaceni pres swipe byla nejpozadovanejsi nova vlastnost.
Uplny swipe, tj. nacteni i stranky pred a za a hladky posun pri posunu muze byt slozitejsi. Ale i jednoduche zachyceni gesta a nacteni predchozi/dalsi stranky bez vizualne naznaceneho prechodu by mohlo stacit.

**Comment by ovyhlidal** [comment]
Odstranil jsem label bug z tohoto issue, protoze vetsina problemu byla opravena. Swipe nechavam jako enhancement.

**Comment by ovyhlidal** [comment]
Tohle bude vyreseno v okamziku, kdy se dodela ios nativni ctecka, takze si myslim, ze muzeme tohle issue uzavrit.
