### ISSUE TITLE
U výsledků hledání chybí vyhledávací políčko a hlavní menu

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#133]
Nevím, jestli k tomu nejsou nějaká pravidla, ale očekával bych v seznamu výsledků vyhledávání i vyhledávací pole a dole i hlavní menu.

**Comment by ovyhlidal** [comment]
V soucasne dobe aplikace je navrzena jinak a predelani neni uplne trivialni. Kazdopadne muzeme se domluvit na upravach ...

**Comment by zabak** [comment]
OK, nebudeme řešit
