### ISSUE TITLE
Pád aplikace při mazání dotazu z našeptávače

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#137]
Vyhledávám v MZK. Napíšu Clap . Našeptávač nabídne Oh, Kay!... - vyberu to.  Appka vátí červenou hlášku nenalezeno. Zmáčknu backspace. Smaže se jeden znak z vyhledávacího dotazu (t na konci) a asi za sekundu aplikace spadne. U některých jiných dotazů to nedělá. Lze před backspace tapnout doprostřed textu a pak mazat. Padá to i při napsání jednoho písmene do dotazu - ale tam to trvá asi 3 sekundy než to spadne.

**Comment by ovyhlidal** [comment]
Cervena hlaska se zobrazuje kvuli tomu, ze pri psani zrusim predchozi requesty na naseptavani a neosetril jsem situaci s error kodem pro zruseni requestu. Padani bude opraveno v dalsim releasu 1.2.0 (build 2)
