### ISSUE TITLE
Prehled titulu v kolekci

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/kramerius-for-ios#14]
•	Sirka sloupcu asi definovana natvrdo pro telefon, na tabletu zbytecny prazdny pruh uprostred
•	Malo udaju o titulu (pouze hlavni nazev - nestaci)
•	Klik na libovolny titul casto zpusobi pad appky
![img_3790](https://cloud.githubusercontent.com/assets/16186956/11622612/5a7fc560-9cc7-11e5-8536-507f62fde15c.PNG)

**Comment by honza-rychtar** [comment]
> Malo udaju o titulu (pouze hlavni nazev - nestaci)

@jankanka Jake dalsi udaje byste tady chtel?
V API je nazev z DC, takze je to hlavni nazev zretezeny s podnazvem.
Dale je tam thumbnail, autor(i) a typ dokumentu.

Androidi klient, alternativni webovy klient i oficialni webovy klient zobrazuji stejna data.

## Android:
![screen](https://cloud.githubusercontent.com/assets/1178142/11625270/f7bf5144-9cd9-11e5-86df-5b6391ae0edf.png)

## Alternatini webovy klient:
![snimek z 2015-12-07 12 07 20](https://cloud.githubusercontent.com/assets/1178142/11625556/1396aa1e-9cdc-11e5-8302-8475b0f192eb.png)

## Oficialni webovy klient
ten dokonce v novinkach (stejna obrazovka jako u iOS, Android, Alt klient) zobrazuje pouze thumbnailu. 
![snimek z 2015-12-07 12 08 33](https://cloud.githubusercontent.com/assets/1178142/11625593/58e41cd2-9cdc-11e5-8b0d-823eeba20eac.png)

## Oficialni webovy klient - hledani
tady je stejna podmnozina udaju jako u iOS (a dalsich klientu).
![snimek z 2015-12-07 12 09 20](https://cloud.githubusercontent.com/assets/1178142/11625611/8d3a409c-9cdc-11e5-814b-7b16a16324f0.png)

**Comment by jankanka** [comment]
Co tam nejvice chybi, je rok(y) vydani. Nejbolestnejsi je to u stejnojmennych veci, kdy nedokazu odlisit jednoltive tituly a zjistit, zda jde onejakou duplicitu apod. Priklad v teto prtezentaci, slide 4. 
https://docs.google.com/presentation/d/19C2wu2RxNS8Q0GXOUerOr4g_QE_nH7pR2P-1GqiZVOM/edit?usp=sharing
V nasem (= zlinskem) Krameriovi se nam nezobrazuji ani podnazvy, coz jeste vetsi masakr - nevim, v cem je problem, zda se to da nejak nastavit :(

**Comment by honza-rychtar** [comment]
Slide 4 - dokument hlidka:
Tohle je chyba v datech. Periodikum je tam 4x, konkretne:
1) http://janrychtar.cz/kramerius/#/ndk/periodical/uuid:f66790e0-4449-11e2-9b88-005056827e51 (pouze rocnik 1907)
2) http://janrychtar.cz/kramerius/#/ndk/periodical/uuid:925fecc0-4a2d-11e2-abe9-005056827e51 (pouze rocnik 1935)
3) http://janrychtar.cz/kramerius/#/ndk/periodical/uuid:9a63ed40-4a2d-11e2-abe9-005056827e51 (pouze rocnik 1939)
4) http://janrychtar.cz/kramerius/#/ndk/periodical/uuid:c56dce20-1cf1-11e2-bec6-005056827e51 (spousta rocniku)
Rocnik 1907 v 4) chybi, rocniky 1935 a 1939 jsou v 4) znovu (nove naskenovane).
Spravne reseni je nechat pouze jeden zaznam pro periodikum - 4) 
Do nej presunout rocnk z 1) a rocniky z 2) a 3) bud smazat nebo vybrat "hezci" skeny a nebo je duplikovat - ale ne na urovni periodika - az v seznamu rocniku muzou byt rocniky zopakovany,
Kdyz si proklikate ty 4 odkazy, tak se kouknete vpravo do vypisu metadat - jsou totozne, vcetne signatury.

Z pohledu klienta neni jak tyto 4 dokumenty rozlisit - vypsanim rocniku jen prohloubim chybu v duplikaci - je to 4x to same periodiku se spatnou strukturou. To se musi opravit v datech, potom to budou vsichni klienti zobrazovat spravne.


Slide 3 - chybejici podnazvy ve vasem Krameriovi:
Napr. periodikum http://dlib.kfbz.cz/search/i.jsp?pid=uuid:67da3680-8e53-11e2-af36-00155d01270c
Nazev: Zlín 
Podnazev:  Sdělení zaměstnanců firmy Baťa
V MODSu je nazev i podnazev - http://dlib.kfbz.cz/search/api/v5.0/item/uuid:67da3680-8e53-11e2-af36-00155d01270c/streams/BIBLIO_MODS
V DC by mel byt spravne zretezeny nazev: podnazev (Zlín: Sdělení zaměstnanců firmy Baťa)
Vy tam ale mate pouze hlavni nazev (Zlín) - http://dlib.kfbz.cz/search/api/v5.0/item/uuid:67da3680-8e53-11e2-af36-00155d01270c/streams/DC
Z DC se pak generuje API: http://dlib.kfbz.cz/search/api/v5.0/item/uuid:67da3680-8e53-11e2-af36-00155d01270c
a SOLR: http://dlib.kfbz.cz/search/api/v5.0/search?q=PID:%22uuid:67da3680-8e53-11e2-af36-00155d01270c%22
kde tim padem podnazev vubec neni. Vysledky hledani se berou ze SOLR a proto podnazvy u vasich dokumentu v klientech nejsou zobrazeny.
Diky absenci podnazvu v SOLRu take nelze podle podnazvu v Krameriovi vyhledavat.

DC se generuje bud z MARCu nebo MODSu (v obou podnazvy jsou). Podle @pavluska to zalezi na firme, ktera u vas digitalizaci provadela - jak nastavila sablony pro generovani DC - at uz umyslne nebo chybou se podnazvy pri generovani ignorovaly.

**Comment by jankanka** [comment]
Dekuju za podrobnou analyzu. Ad Hlidka - jasne, takovych bude vic a bude se na ne prichazet postupne. Ad Zlin - toho jsem se obaval :( Je nejaka moznost, jak si to preindexovat / pretvorit? Tahle data pochazeji z let 2005-2008 a delal je Elsyst - stejne jako spoustu dalsich zakazek v te dobe. Byla to data urcena pro K3, nemohlo se nekde neco vytratit cestou pri jejich importu do K5?

**Comment by honza-rychtar** [comment]
Tak u starsich dokumentu je stejny problem i v MZK Krameriovi.
Napr. Davidova houpacka:
MODS http://kramerius.mzk.cz/search/api/v5.0/item/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6/streams/BIBLIO_MODS obsahuje podnazev, ktery neni v DC: http://kramerius.mzk.cz/search/api/v5.0/item/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6/streams/DC

Podle @pavluska to bylo zpusobeno pri konverzi K3 -> K4.
Ve vasem pripady by asi bylo nejjednodussi to opravit rucne tak, ze zaznam vytahnete z fedory, upravite DC a vlozite jej zpatky.
Mate 520 monografii, u kterych podvazvy asi potreba nebudou.
A 75 periodik, ktere se daji rychle proletet a identifikovat ty, kde by bylo vhodne podnazev doplnit a pak je rucne zmenit.
Pripadne bych vam mohl napsat skript, ktery by nasel vsechny dokumenty, ktere maji v MODSu podnazev, ktery neni obsazen v DC.title

Z meho pohledu by bylo nejlepsi DC pro ucely SOLR a API vubec nepouzivat a nazev a podnazev brat z MODS a uchovavat je jako dve pole.
Uz v klientech by bylo peknejsi, kdyby nazev byl vyraznejsim vetsim fontem a podnazev by se zobrazil pod nazvem mene vyraznym mensim fontem. Dalo by se to rozdelit pres tu dvojtecku, ale lepsi je to mit strukturovane na urovni dat.

**Comment by ovyhlidal** [comment]
Ohledne chyb v aplikaci - opraveno. 
Necham tohle issue otevreno, ale dam mu jiny label.

**Comment by jankanka** [comment]
Smutne je, ze se to takhle chova prave i u tech monografii, ktere se digitalizovaly a popisovaly az v letech 2012-13 v krajskem projektu dle tehdy platnych standardu NDK. Ty uz pres K3 vubec neprosly...

**Comment by ovyhlidal** [comment]
Opraveno jiz drive.
