### ISSUE TITLE
Prohlížečka stránek zobrazí jen roztažený náhled

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#142]
Teprve až se člověk pokusí o zoom, tak se dotáhne zaostřený obrázek

**Comment by ovyhlidal** [comment]
V jakem dokumentu se tak deje? 
Abych mohl vyse zminene chovani reprodukovat a analyzovat.

**Comment by zabak** [comment]
Ve všech co nejsou jpg ale zoomify. Např. Malovaná mládež.

**Comment by zabak** [comment]
ale zdá se že to dělají i Šachy.

**Comment by zabak** [comment]
i mapa Stát Československý

**Comment by Fiser33** [comment]
Toto chovani je opraveno ve verzi 0.1.5 knihovny iOSTiledViewer. Je zminena verze pouzita v aplikaci dostupne na TestFlight?

**Comment by ovyhlidal** [comment]
Toto jeste neni na Testflightu, dneska budu uploadovat build...

**Comment by ovyhlidal** [comment]
Opraveno ve verzi 1.2.0 build 4.
