### ISSUE TITLE
pád aplikace při listování

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#144]
Dám hledat slovo Atlantis. Dostanu seznam rukopisů. Libovolný z nich vyberu a začnu listovat. Aplikace spadne na ios 9 po otočení druhé stránky, na ios 10 po otočení cca 4. stránky.

**Comment by ovyhlidal** [comment]
Jedna se o problem ve ctecce, kterou pise Jakub. Je mozne ho pridat sem? Mam tady primo log, kde je videt problem s pristupu k optinal value, ktera je nil...

**Comment by zabak** [comment]
Ok přidal jsem ho, musí to ale potvrdit

**Comment by Fiser33** [comment]
Toto bylo opraveno ve verzi 0.1.5, ktera by jiz mela byt pouzita v aplikaci na TestFlightu. Prosim o kontrolu.

**Comment by zabak** [comment]
vyřešeno
