### ISSUE TITLE
Zrusit prouzek <- -> v prohliecce

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#146]
Proc je tam ten prouzek (<- ->). Po chvilce pouzivani me to tam neskutecne stvalo. Ja chci klikat do prazdnych prostoru na krajich nebo swypovat pro otaceni stran. Nechci se trefovat do nejakeho prouzku s sipkama, ktereho se nemam jak zbavit a strasne tam rusi.
A vubec ty ovladaci prvky zabiraji strasne moc mista i na 10" zarizeni.

@zabak 
> Tohle byl důsledek problému, že se nedá rozlišit u nazoomované stránky swipe a posun obrázku. V Androidu to řešíme tak, že swipe na otočení stránky se detekuje jen při plně zobrazené stránce a jinak se stránka otočí tapnutím v dolní nebo pravé (strana dopředu), resp. horní nebo levé (strana zpět) části obrazovky. Myslím, že by to mohlo takto fungovat a šedá pruh lze zrušit. Navíc ještě navrhuju (i pro Android) že pokud u zazoomovaného obrázku dojedu na jeho okraj a znovu udělám swipe, tak se stránka otočí taky.

@ovyhlidal 
> Na iOS neni defaultni chovani tapnuti na horni/dolni okraj obrazovky. Defaultni chovani prepinani stranek je tapnuti na okraj obrazovky, ktere funguje i kdyz ma uzivatel zazoomovano. Bohuzel je tady kolize v pouziti tap gesta. Kdyz chci tapnout na okraj obrazovky, tak je odpali tap, ktery je pouzit pro zobrazeni/skryti ovladaci listy. Muzu jeste zkusit pohrat si s nastavenim tap gesture recognizeru, ale nemuzu zarucit, ze to bude fungovat. Swipe na otoceni stranky funguje pri odzoomovane strance. Myslim si, ze reseni v podobe polopruhlednych tlacitek je lepsi nez pridavat dalsi gesto.

**Comment by honza-rychtar** [comment]
Jake dalsi gesto chces pridavat?
Kdyz tapnes, tak nejaky onTouch callback ti urcite dava x,y pozici ne? Rozmery znas taky.
Pak staci
a) x < width/5 => predchozi stranka
b) x > width - width/5 => nasledujici stranka
c) jinak => zobrazit/schovat listy

**Comment by ovyhlidal** [comment]
Toto bude opraveno v dalsi verzi 1.2.0 build 4.
