### ISSUE TITLE
Zpěvy mladosti -  pád aplikace

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#147]
Spustím aplikaci, knihovna MZK. Zvolím nejnovější, vyberu knihu Zpěvy mladosti. Začne se načítat stránka a po chvíli aplikace spadne.

**Comment by ovyhlidal** [comment]
S novou verzi ctecky se mi toto nedari reprodukovat ... Zitra zkusim otestovat jeste i na ipadu.

**Comment by zabak** [comment]
funguje, zavírám
