### ISSUE TITLE
Zoomování - rozbité obrázky

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#148]
Obrázky stránek v dlaždicích zoomify nejsou korektně zobrazeny - např. v kniže Šachy (MZK, Zajímavé) se levá horní část stránky zobrazí v pořádku a zbytek stránky je různě roztažený.

**Comment by ovyhlidal** [comment]
Toto bude opraveno v dalsi verzi 1.2.0 build 4, je nutne updatovat knihovnu pro zoomify.

**Comment by zabak** [comment]
opraveno, zavírám

**Comment by zabak** [comment]
tak otevírám - Zpěvy mladosti z #147 obrázek obálky - je zobrazena jen 1/4 a částečně deformovaná.

**Comment by ovyhlidal** [comment]
Toto je pro @Fiser33. Muzu se na to taky podivat.

**Comment by ovyhlidal** [comment]
Toto by melo byt take vyreseno s nejnovejsim updatem knihovny na vykreslovani dokumentu, pri mem testu se tato chyba neprojevila. K sirsimu testovani bude oprava dostupna ve verzi 1.3.0 build 1.

**Comment by zabak** [comment]
vyřešeno, zavírám
