### ISSUE TITLE
Pruh vlevo po stisku modreho ctverecku

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/kramerius-for-ios#15]
•	(modry ctverecek moc nepripomina tlacitko)
•	nazev knihovny se urezava vpravo namisto zalomeni
•	Prehravac - kdyz ho spustim odtud, nevim, jak zvolit neco k prehrani; "i" vpravo nahore nedela nic (ani kdyz neco hraje); nefunguje casomira prehravani; pri prehravani se zpbrazi jen nahore v modrem pruhu nazev skladby, zbytek (tj 95% displeje) zustava prazdny
•	Hledani - vede na prazdnou obrazovku bez moznosti jakehokoli zadani dotazu; hledani na obrazovce s prehledem titulu zpusobi pad appky pri zadavani textu (priklad slovo "hrůza", po zadani ctvrteho pismene appka spadne)
•	Nastaveni a napoveda zatim nefunguji

![img_3789](https://cloud.githubusercontent.com/assets/16186956/11622656/940a07a0-9cc7-11e5-9e80-044ad1c95190.PNG)
![img_3792](https://cloud.githubusercontent.com/assets/16186956/11622662/9a78c4a0-9cc7-11e5-921f-948ade96ef3d.PNG)
![img_3791](https://cloud.githubusercontent.com/assets/16186956/11622665/a4f914d4-9cc7-11e5-92cb-8960ced2ecb6.PNG)
![img_3788](https://cloud.githubusercontent.com/assets/16186956/11622680/bc4cc78e-9cc7-11e5-8b5b-7c6a7cf8f5d9.PNG)

**Comment by ovyhlidal** [comment]
• (modry ctverecek moc nepripomina tlacitko) - problem v grafickem assetu

• nazev knihovny se urezava vpravo namisto zalomeni 

• Prehravac - kdyz ho spustim odtud, nevim, jak zvolit neco k prehrani; "i" vpravo nahore nedela nic (ani kdyz neco hraje); nefunguje casomira prehravani; pri prehravani se zpbrazi jen nahore v modrem pruhu nazev skladby, zbytek (tj 95% displeje) zustava prazdny - opraveno

• Hledani - vede na prazdnou obrazovku bez moznosti jakehokoli zadani dotazu; hledani na obrazovce s prehledem titulu zpusobi pad appky pri zadavani textu (priklad slovo "hrůza", po zadani ctvrteho pismene appka spadne) - hledani jeste neni dodelane

• Nastaveni a napoveda zatim nefunguji - momentalne neni co zobrazit v nastaveni. Napoveda a zpetna vazba je v podstate informace o aplikaci, ktere zatim neni pushnute.

**Comment by honza-rychtar** [comment]
@ovyhlidal Rikal jsi, ze na iOS neni zvykem mit obrazovku s nastavenim primo v aplikaci. Drzme se zvyklosti iOS, ne Androidu. Takze nastaveni klidne odstran.

Predpokladam, ze "Prehravac" v hlavnim menu je jen pro testovaci ucely. Prehravac by se mel otevrit, az kdyz otevru zvukovy dokument (model soundrecording).
Taky jsme to na Androidu upravili tak, ze po kliku na zvukovy dokument (soundrecording) se rovnou otevre prehravac se seskupenyma trackama ze vsech soundunits, tj. preskoci se vrstva vybrani soundunit. Doporucuju to udelat stejne na iOS.

**Comment by ovyhlidal** [comment]
@honza-rychtar Nastaveni odstranim.
Ohledne prehravace to je bug. Mam to ted navrhnuty tak, ze pokud uzitel spusti hudebni prehravani, tak se mu prida do menu polozka hudebni prehravac a zustane tam s tim, ze tam bude mit vzdycky posledni hudbu co prehraval. Mam bug v tom pridavani do menu, ktery jeste pred releasem opravim. 

Co se tyka seskupovani tracku, tak s tim problem nemam, ale nejspis to nestihnu predelat do tohodle releasu.
