### ISSUE TITLE
Zámek zoomu při listování

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#155]
Vytvořeno na základě požadavku vzešlého při řešení #40: Pokud uživatel zazoomuje na určitou část stránky, při otočení na další stranu by měl být tento zoom zachován. 

@jandera: pokud se má toto realizovat, musela by aplikace vědět, jak se chovat a to se bude lišit podle toho o jaký dokument jde. Je jasné, že by měl být při listování zachován zoom level, jakou část stránky má ale zobrazovat, to už tak jednoduché není a proto prosím o vylepšení toho jak by to mohlo vypadat: 

- při otočení zůstane zobrazena stejná část nové stránky jako u stránky předešlé. Toto je vhodné pokud jsem jen zvětšil obrázek tak, abych viděl potištěnou část stránky a ne její okraje. Pokud ale zvětším stránku tak, že vidím na výšku jen několik řádků, při čtení skončím dole a na další stránce bych potřeboval skočit nahoru. Navíc text na sudých a lichých stranách nemusí být na stejném místě, takže by uživatel musel stejně posouvat stránkami doprava a doleva. Mělo by to tedy být tak, že se na další stránce skočí do levého horního rohu, pokud nebyla zobrazena celá?

**Comment by jandera** [comment]
Pokud bych si mohl zazoomovat a vystredit stranku tak, abych ji mel na display celou, tak by stacilo splnit jednu podminku - zachovat zoom a zarovnat stranku do leveho horniho rohu. Toto by melo vyhovovat napr. i pri cteni novin, kdy mam zazoomovano vic, abych precetl clanek, a pri otoceni se mi zobrazi dalsi strana zarovnana od zacatku. Melo by to vyhovovat i pri cteni na sirku, kdy si stranku roztahnu na maximalni moznou siri strany a pak posouvam dolu.
Nyni, ale kvuli krokovemu zoomovani, ktere je jeste dost hrube, si stranku celou na display vetsinou nedam, tak abych ji pohodlne precetl, roztahnout stranku na maximalni siri take vetsinou nejde a jeste se nemohu prepnout do cteciho modu.

**Comment by zabak** [comment]
To krokové zoomování je už ve verzi 1.2.0 vyřešené, pro externí testery to teď apple musí schválit, snad to nebude trvat dlouho. Pak si to budete moct otestovat.

**Comment by jandera** [comment]
Otestováno. Nyní se stránka zobrazí s maximálním využitím displaye, takže v mnoha případech zámek zoomu není potřeba. Pokud si zapnu zámek zoomu, např. při čtení novin nebo při čtení na šířku tak na další stránce bych chtěl číst od začátku, tedy od levého horního rohu. Pokud bych listoval zpět (nebo na již načtenou stránku), tak bych se chtěl vrátit tam, kde jsem stránku opustil - tak se to teď už chová, zoom zůstává zachován a poloha stránky také, jen jsou stránky rozostřené ať zazoomované nebo ne.

**Comment by ovyhlidal** [comment]
- (bug 1) toto vyresim s Jakubem. 
- (bug 2) zamek zoomu je soucasti vykreslovaci casti. Pro prvni fazi bych obnovil puvodni chovani - odzoomovani po prepnuti stranky. V okmaziku kdy implementujeme zamek zoomu, tak by to melo byt ok.  
- (bug 3) tady se nejedna o bug, spis se musime shodnout v tom, jak ma fungovat prepinani stranek. V okamziku, kdy uzivatel zazoomuje dokument, tak stanovene regiony pro prepinani stranek jsou definovane stale stejne, tzn 1/5 z prava a leva. V pripade, ze chci prepnout na predchozi stranku, tak musim kliknout do 1/5 definovane od leveho okraje dokumentu a ne od okraje displaye. Diky tomu, ze zobrazeni dokumentu ma na starost Jakubova knihovna, tak toto reseni bylo zvoleno jako nejjednodussi pristup.

**Comment by zabak** [comment]
(bug 3) - regiony by se měly vztahovat k displeji - právě kvůli tomu zoomování

**Comment by zabak** [comment]
(bug 2) - vyřešeno
