### ISSUE TITLE
Stahovani virtualnich sbirek se chova divne

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#161]
Stahovani virtualnich sbirek trva moc dlouho a zobrazuji se prazdne radky...

**Comment by MartinRumanek** [comment]
Dost možná je to chyba Krameria, konkrétně nejnovější verze 5.3.6.


Mohl bys to prosím potvrdit/vyvrátit?

**Comment by ovyhlidal** [comment]
Mrknu se na to poradne pristi tyden, vsiml jsem si toho, kdyz jsem delal video na prezentaci k obhajobe diplomky. Kazdopadne si myslim, ze pred mesicem to tak nebylo. Co jsem zkousel treba knihovnu v Olomouci, tak tam se to nacetlo pomerne rychlejs...

**Comment by zabak** [comment]
Řeší Marek, je to na straně Krameria

**Comment by zabak** [comment]
vyřešeno
