### ISSUE TITLE
Posuvník v detailu - dotek na kdekoli na ose by měl otočit stárnku o jednu daným směrem

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#17]
Původní nadpis požadoval skočit na dané místo na ose, to ale není dobrý nápad, není to přesné.

**Comment by ovyhlidal** [comment]
Toto neni uplne standardni chovani slideru, takze se tato funkcionalita musi rucne dopsat.

**Comment by zabak** [comment]
Aha - v tom případě to není priorita.

**Comment by zabak** [comment]
Možná lepší chování by bylo, že když se dotknu osy, tak by se měl otočit jen o jednu stránku daným směrem. @honza-rychtar nebylo by takové chování lepší i na androidu?

**Comment by honza-rychtar** [comment]
V tom pripade je ten posuvnik zbytecny. Pro otoceni stranky o jednu tam jsou kraje obrazovky (a swype). Posuvnik by mel plnit 2 funce:
1) Informuje v jake casti knihy jsem - jednak textove AKTUALNI_STRANA/POCET_STRAN a pak vizualne pozici toho soupatka.
2) Muzu se diky nemu rychle pohybovat v dokumentu. 
Pokud mam 500 stranek a chci nalistovat doprostred, tak po jedne je budu tozko otacet - k tomu mam ten posuvnik, abych se posunul kam chci.

**Comment by zabak** [comment]
Jo pravda, zapoměl jsem že nejde o finální podobu prohlížečky. Zavírám.

**Comment by honza-rychtar** [comment]
@zabak Ja narazel i na:

> Možná lepší chování by bylo, že když se dotknu osy, tak by se měl otočit jen o jednu stránku daným směrem. @honza-rychtar nebylo by takové chování lepší i na androidu?

Nevidim duvod, proc by se chovani menilo na Androidu (viz predchozi odpoved).
