### ISSUE TITLE
Logo zvolené knihovny zobrazovat na bílém pozadí

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#19]
Například stejně jako na Androidu v bílém kruhu. Jinak hlavně do modra laděná loga splývají s modrým pozadím.

**Comment by LenkaDamborska** [comment]
Neříkal Ondra, že loga v iOSu nemívají pozadí?

**Comment by honza-rychtar** [comment]
@LenkaDamborska Tim myslel ikonu aplikace, ktera se ti zobrazi na domovske obrazovce v telefonu nebo ve vyberu aplikaci. 

@zabak Tohle chci zmeni na androidu. Kruhova loga vypadaji v bilem kruhu divne a taky svetla loga budou spatne viditelna.

**Comment by zabak** [comment]
@honza-rychtar Ne, fakt jsem myslel loga jednotlivých knihoven - podívej jak vypadá třeba logo NDK, které je modré na modrém pozadí. Na androidu je máš všechna v bílém kruhu. Loga jsou dělaná tak, aby byla vidět na bílém pozadí (protože se obvykle tisknou na papír) takže pokud by podklad zvoleného loga byl bílý a ne modrý, je to ok.

**Comment by honza-rychtar** [comment]
@zabak No vsak ja taky - ja jen reagoval ke komentari od @LenkaDamborska, ze loga v iOS nemaji pozadi se vztahovalo k ikonam aplikace.
Zbytek jsem bral z pohledu loga v aplikaci. A bili kruh taky neni nejlepsi reseni, napr.

![s](https://cloud.githubusercontent.com/assets/1178142/11679974/58709f62-9e55-11e5-975e-c23ac38b2625.png)

Lepsi by bylo mit dostatecne kontrastni pozadi (ne bile) vuci logu pro kazde logo/ikonu.

**Comment by zabak** [comment]
Jo jasně :-)

Co místo koleček dát bílý podklad na celou výšku toho modrého pruhu - takový čtverec, kde by byla dole jen tenká bílá linka? Název knihovny by zůstal na modrém pozadí. Nevýrazná loga budou sice nevýrazná, ale jinak bychom museli studovat které barvy podkladu se hodí k jakému logu, co říká případný design manual k příslušným logům apod.

**Comment by ovyhlidal** [comment]
Toto neni problem zmenit, jen zalezi na jakou barvu, pripadne jak se to ma chovat?

**Comment by zabak** [comment]
V této verzi bych možná jen změnil podklad na hodně světlý nebo přímo bílý, prostě co je nejjednodušší.

**Comment by ovyhlidal** [comment]
Ok, zmenim podklad na bilou.
