### ISSUE TITLE
Chybí volba Naposledy hledané

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#21]
Navrhuji dát ji do horního modrého menu vedle Nejnovějších a Doporučených.

**Comment by ovyhlidal** [comment]
@zabak  Tim padem by naposledy hledane polozky byly pristupne pouze z hlavni obrazovky, kde je nahore prepinac? Aktualne vypada hledani v hlavni obrazovce nasledovne:
![simulator screen shot 09 dec 2015 13 57 56](https://cloud.githubusercontent.com/assets/11073775/11685918/f2441bec-9e7c-11e5-9e3a-56dd089500db.png)
![simulator screen shot 09 dec 2015 13 57 32](https://cloud.githubusercontent.com/assets/11073775/11685919/f2443f32-9e7c-11e5-8fed-20137f8fae88.png)
![simulator screen shot 09 dec 2015 13 57 24](https://cloud.githubusercontent.com/assets/11073775/11685920/f2459d1e-9e7c-11e5-8624-3b02edf3ec2d.png)

Je moznost udelat to, ze kdyz user klikne do pole hledani, tak ze mu zobrazi naposled vyhledane tituly. Tim padem by se dala uplne vynechat obrazovka Hledani z menu. 

Momentalne kdyz uzivatel zada hledany text, tak neni presunut do obrazovky hledani, ale naseptavani probehne primo zde a pak podle vybraneho titulu se bud otevre prohlizec sbirek, nebo prehravac nebo prohlizecka...

**Comment by zabak** [comment]
@honza-rychtar co si o tomto návrhu myslíš?

Ony jsou to mimo jiné dokumenty u kterých si aplikace pamatuje, kde uživatel přestal číst, nevím jestli bude stačit je zpřístupnit takto.

**Comment by honza-rychtar** [comment]
@zabak Naposledy hledane dokumenty nedavaji smysl. 
Pouzivame naposledy otevrene dokumenty - ty ale nemaji s hledanim nic spolecneho, ty proste uzivatele otevrel, at uz se k nim dostal jakkoliv.

Je mozne ukladat naposledy hledane vyrazy - **historie hledani** - (to jste mozna mysleli), tj. textove retezce, ktere uzivatel ve vyhledacim poli uz nekdy zadal - rucne, nebo pres naseptavac.

Potom by se naseptavac mohl predvyplnit treba peti retezci z **historie hledani** jeste nez uzivatel zacne psat hledany text. Jakmile uzivatel zacne psat text, tak se nejdriv zobrazi (napr. max 3) vyfiltrovane retezce (podle zadaneho textu) z **historie hledani** a za ne se zobrazi online nalezene vysledky. Typ vysledku v naseptavaci by se odlisil ikonou (hodiny/lupa).

Priklad z Google Play pro Android:
Posledni dve hledani byly *test* a *test 2*

* Klikl jsem do vyhledavaciho pole a jeste nezacal psat text
![screenshot_20151210-110322](https://cloud.githubusercontent.com/assets/1178142/11712833/cdc0c51e-9f2f-11e5-9047-e0190fec20de.png)

* Zacal jsem psat text **te**
![screenshot_20151210-110350](https://cloud.githubusercontent.com/assets/1178142/11712857/eb3a8b48-9f2f-11e5-8c92-10c8ad9b0647.png)



Takto bych to mohl udelat v Androidim Krameriovi.

**Comment by zabak** [comment]
Omyl, myslel jsem naposledy otevřené, ne naposledy hledané :-(

**Comment by honza-rychtar** [comment]
@zabak Takze navrhujes na iOS mit *naposledy otevrene* jako dalsi tab?
Tim by tam uz byly minimalne 4 - doporucene, nejnovejsi, sbirky, naposledy otevrene.

To co navrhoval @ovyhlidal 
> Je moznost udelat to, ze kdyz user klikne do pole hledani, tak ze mu zobrazi naposled vyhledane tituly. Tim padem by se dala uplne vynechat obrazovka Hledani z menu.

Si nedokazu predstavit (pokud tim taky myslel naposledy otevrene). Nalezenych vylsedku podle ruznych kriterii bude silene moc, To si je mam vsechny ukladat a prirazovat k nejakemu klici? Co kdyz jsem naposledy hledal *vse* - kolik tech nalezenych vysledku si mam pamatovat? Navic za dva dny uz se to bude lisit, protoze pribyly nove dokumenty. 
Pro uzivatele dava smysl pamatovat si opravdu otevreny dokument a stranku, na ktere dokument zavrel. A potom hledane vyrazy, ktere v minulosti odpalil ve vyhledavacim poli.

Takze naposledy otevrene dokumenty bude stale potreba mit odnekud pristupne (ne z hledani).

A pokud jde o ten muj navrh k **historii hledani**, tak to bychom mohli udelat pro iOS i Android - co vy na to?

**Comment by zabak** [comment]
@honza-rychtar Ano, jako další tab. Souhlasím že to co navrhuje @ovyhlidal není ono, jednodušší je mít tam klasický našeptávač. Využít do našeptávače historii hledání jak navrhuješ je dobrý nápad, souhlasím.

**Comment by ovyhlidal** [comment]
Pokud nebude zadna historie hledani hadam, ze tab nema vubec zobrazovat?

**Comment by zabak** [comment]
Lepší je mít ji prázdnou - pokud člověk poprvé něco zahledá, tak se naplní. Ale mást lidi tím, že po instalaci tam historie není a pak se najednou objeví...? 
@honza-rychtar co říkáš?

**Comment by zabak** [comment]
Považuju za vyřešené, pokud bude třeba, tak se otevře nové issue.
