### ISSUE TITLE
Pole pro hledání přizpůsobit ios zvyklostem

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#24]
Například takto
![image](https://cloud.githubusercontent.com/assets/5516936/11709822/f6f59708-9f1a-11e5-8cf8-592351d54f75.jpeg)
![image](https://cloud.githubusercontent.com/assets/5516936/11709823/f6f688d4-9f1a-11e5-887b-2fca1aaef561.jpeg)

**Comment by ovyhlidal** [comment]
V nejnovejsi verzi, ktera jeste neni publikovana je hledani predelano a vypada standardne. 
![simulator screen shot 10 dec 2015 14 25 35](https://cloud.githubusercontent.com/assets/11073775/11716397/e6c79280-9f49-11e5-9261-4bda9834c86a.png)
![simulator screen shot 10 dec 2015 14 25 30](https://cloud.githubusercontent.com/assets/11073775/11716398/e6c9df90-9f49-11e5-89ea-b4f6e153b1de.png)
