### ISSUE TITLE
Náhledy jsou špatně použitelné, minimálně na iPhone

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#25]
Na menším displeji telefonu jsou náhledy příliš malé. Přikláněl by se k tomu, aby byla zaplněna celá plocha. A "sešil" bych strany k sobě. Tím by zmizel ten nevyužitý černý pruh.

![image](https://cloud.githubusercontent.com/assets/5516936/11710024/7ea05e4e-9f1c-11e5-8cb2-278098425e4c.png)

**Comment by ovyhlidal** [comment]
Opraveno.
![simulator screen shot 10 dec 2015 12 41 05](https://cloud.githubusercontent.com/assets/11073775/11714558/4d7b6c2c-9f3b-11e5-9d31-3462c8e05191.png)
