### ISSUE TITLE
Výběr stránek sliderem

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#27]
Osobně bych slider nechával skrytý a zobrazil například po delším podržení prstu. Podobně jsou skyty ovládací prvky napřiklad v Safari. U stávajícího slideru nyní dojde ke změně čísla stránky až po ukončení doteku. Není tedy možné jít na konkrétní stranu, protože její číslo vidím, až po dokončení akce.

**Comment by ovyhlidal** [comment]
Jestli jsem to pochopil spravne, tak v podstate jde o to, ze pri tahu slideru se neaktualizuje cislo v pravo od nej, ktere ukazuje aktualni stranku. Opravim to tak, aby pri pohybu slideru se v pravo ukazovalo aktualni cislo stranky.

**Comment by black23** [comment]
Ano. Ale ten slider zabírá poměrně nezanedbatelný prostor, minimálně na mobilu. Co ho schovat, pokud není třeba?

**Comment by ovyhlidal** [comment]
Horni i spodni bar se da schovat pomoci jednoho tapu do prostoru, kde je vykresleny obsah. Opetovnym tapem se daji bary zobrazit.

**Comment by black23** [comment]
Ano, tak to opravdu funguje, ale ty centimetrové nevyuźité pruhy zůstanou. Je to detail, ale nezda se mi to šťastné :-)
