### ISSUE TITLE
Při zamknutí disleje by mělo být možné ovládat audio přehrávač

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius-for-ios#28]
Je to standardní přístup u aplikací, které přehrávají audio
![image](https://cloud.githubusercontent.com/assets/5516936/11723414/9dd06456-9f6e-11e5-9c74-4230899d18f3.png)

**Comment by ovyhlidal** [comment]
Toto chovani mam v planu udelat, jen to urcite nebude ted do predvanocniho releasu.

**Comment by ovyhlidal** [comment]
Toto jiz v prehravaci funguje.
