### ISSUE TITLE
přehrávání zvuku nefunguje

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#30]
posuvník ukazuje, že přehrávání jede, ale nic neslyším. Hlasitost je přitom nastavená dobře, jiné aplikace slyšet jsou

**Comment by ovyhlidal** [comment]
Ve ktere verzi se tento bug projevil?

**Comment by zabak** [comment]
zatím ve všech (i v 1.0.6). Přitom přehrávání v aplikaci youtube na stejném tabletu funguje (tj. není to problém tabletu nebo hlasitosti)

**Comment by zabak** [comment]
Oprava - přehrává, ale jen do sluchátek.

**Comment by ovyhlidal** [comment]
Jedna se o bug se spatnym smerovanim zvuku, oprava by nemela byt narocna.

**Comment by ovyhlidal** [comment]
Nebyl jsem schopny toto chovani reprodukovat, je mozne udelat regresni test, zda se to jeste projevuje?

**Comment by zabak** [comment]
Už to funguje, alespoň na ipad mini s aktuální verzí iOS
