### ISSUE TITLE
aplikace spadne při otevření některých monografií

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#35]
Z MZK - Zajímavé:
- aplikace spadne při otevření: 
Jules Verne - Dva roky prázdnin
Shakespeare - Hry
Čapek - čtení o TGM
Šachy
Kožuchy
6 pieces
Atlas starého světa
Duha

- náhledy fungují, ale nezobrazí se stránka (obrazovka zůstane černá):
Mácha - Máj
Rovnost

- funguje: 
Když slunéčko svítí
Malovaná mládež
Ztracená
Cestopis
Lidové noviny
Davidova houpačka

**Comment by ovyhlidal** [comment]
Zjistil jsem proc aplikace pada, opravim. V podstate se jedna opet o problem v tom, ze server posle jina data nez aplikace ocekava nebo na ktera je pripravena ...

**Comment by ovyhlidal** [comment]
Pady aplikace jsou opravene. Zobrazeni cerne obrazovky misto obsahu je obecne problem vyresit.
