### ISSUE TITLE
Periodika - zobrazovat číslo ročníku i rok vydání

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#37]
Teď se zobrazuje jen číslo ročníku, na Androidu obojí. V Rovnosti je to ale navíc pomotané: 1885,1886,1887,1888,1889,**6,7,8**,1893,1894,... přitom Rovnost na Androidu je OK

**Comment by zabak** [comment]
A zároveň aplikovat https://github.com/moravianlibrary/kramerius-for-android/issues/242 - tj nahoru rok vydání a pod to teprve ročník

**Comment by honza-rychtar** [comment]
Seznam rocniku Rovnosti: http://kramerius.mzk.cz/search/api/v5.0/item/uuid:f1c7c08d-8f64-4b66-be28-5f209c2c7021/children
V *title* se vsude krom 6. - 8. rocniku pouziva rok vydani, u 6. - 8. rocniku se v *title* pouziva rocnik.
@ovyhlidal U seznamu stranek jsem ti rikal, ze mas radeji brat *title* nez *details.pagenumber* - u stranek je to asi jedno a sam to v kazdem klientovi beru z neceho jineho. 

Ale u seznamu rocniku je potreba to brat z toho *details*:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:f1c7c08d-8f64-4b66-be28-5f209c2c7021/children
rok: *details.year*
rocnik: *details.volumeNumber*

U seznamu cisel rocniku:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:a2a7ab79-aa48-11e1-b7f6-0050569d679d/children
datum: *details.date*
cislo je pak zakernejsi, primarni je *details.issueNumber*, pokud je vyplnene, tak ho pouzij, pokud je prazdne, pak pouzij *details.partNumber*

**Comment by ovyhlidal** [comment]
Opraveno. Ale chtel bych to jeste porovnat s Android klientem... 
@honza-rychtar Mohl bys mi prosim poslat nejake novejsi apk android klienta, abych si to mohl nahodit do simulatoru? Diky

**Comment by ovyhlidal** [comment]
Opraveno.
