### ISSUE TITLE
V NDK  a KNAV se nezobrazí nejnovější

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#41]
Pravděpodobně proto, že je jich hodně a většina je autorsky chráněná

**Comment by honza-rychtar** [comment]
@ovyhlidal Jak ziskavas nejnovejsi?
Pokud to delas pres http://krameriusndktest.mzk.cz/search/api/v5.0/feed/newest a nasledne je vyfiltrujes jen na policy=public, pak by to vysvetlovalo nynejsi chovani, protoze mezi nejnovejsimi 20 dokumenty neni zadny public (v pripade KNAV a NDK).
Spravne je to filtrovat uz na urovni API - http://krameriusndktest.mzk.cz/search/api/v5.0/feed/newest?policy=public - tohle ti vrati nejnovejsi public dokumenty, bez ohledu na to, kolik private dokumentu je novejsich.

**Comment by ovyhlidal** [comment]
Presne tak, filtroval jsem az response ze serveru. Tim padem zviditelnim polozku "Nastaveni" v menu, kde bude moznost prepnout mezi pouze public a vsim. Muzou si uzivatele sami od sebe takhle prepinat nastaveni, nebo to mam udelat jako skrytou volbu?

**Comment by zabak** [comment]
OK, filtrovat se tedy bude na úrovni API a v nastavení bude přepínač. Default bude public a uživatelé budou mít možnost si to přepnout na "všechno". Samozřejmě to znamená, že musejí fungovat hlášky typu "tento dokument není přístupný", protože tohle nastavení umožňuje dokumenty vyhledat, ale zpřístupnění samotné řídí server.

**Comment by ovyhlidal** [comment]
To si myslim, ze neni potreba. Dotazy, ktere posilam pres SOLR tak do nich pridam "dostupnost" a ty ostatni budou filtrovane uz ze strany serveru. V pripade, ze uzivatel prepne nastaveni, tak se znova requesty poslou pro aktualni obrazovku ... V podstate se nepristupne dokumenty nezobrazi, takze hlaska nebude poterba.

**Comment by zabak** [comment]
Když si uživatel nastaví, že chce prohledávat i nedostupné dokumenty, tak se mu zobrazí i nedostupné dokumenty - a pak je potřeba mu je i zobrazit - i když zůstanou nedostupné (mimo thumbnailu). Ale možná každý mluvíme o něčem jiném...

**Comment by ovyhlidal** [comment]
Pokud to chapu spravne: Uzivatel si nastavi aby videl i dokumenty, ktere nejsou public. V ten okamzik se nic nefiltruje, pres api ziskam vsechny dokumenty. Uzivateli je zobrazim, ale v okamziku, kdy je bude chtit otevrit mu zobrazim hlasku, ze je dokument nedostupny(pokud neni public). Tim padem kdy bude umit uzivatel moznost prohlizet obsah, ktery neni public? 
Bude hlaska u nepristupneho dokumentu rikat neco vic nez "tento dokument není přístupný"? Z pohledu uzivatele by tam mohla byt informace, jak vlastne zobrazi ten nedostupny dokument ...

**Comment by zabak** [comment]
U nedostupného dokumentu mohou být stránky, které dostupné jsou - například obálka knihy nebo její obsah. Ta hláška se pak zobrazuje podobně jako v Krameriu, když se zapne vyhledávání přes všechno a zobrazí se nějaká chráněná knížka, tj. je vidět jen thumbnaily jednotlivých stran, ale místo zobrazení dané stránky se objeví hláška že sránka není dostupná. V aktuální verzi klienta pro Android se nezobrazí ani ty thumbnaily aby to člověka nemátlo.

**Comment by ovyhlidal** [comment]
Tak uz se konecne zacinam orientovat :) Dekuju za vysvetleni. Udelam to tedy stejne jako to ma Android, pokud neni pozadavek to mit jinak?

**Comment by LenkaDamborska** [comment]
Asi jste se o tom s Petrem bavili, ale taky bych to udělala jako v Androidu - možnost vybrat, jestli chci vidět veřejné/všechny a pak tam dát hlášku o neveřejnosti dokumentu. Teď je to matoucí, když se nezobrazí dokument ani žádné info, proč tomu tak je.
