### ISSUE TITLE
Hledání nefunguje

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#43]
donekonečna se točí kolečkonahoře vedle ukazatele síly wifi signálu

**Comment by ovyhlidal** [comment]
Tady je pravdepodobne problem v tom, ze posilam text, tak jak jej uzivatel zadal do vyhledavaciho pole. Automaticky se prvni znak pise jako velke pismeno, takze toto opravim. No a pak jeste vylepsim chovani aplikace. Protoze ted pokud prijde prazda odpoved, tak nezobrazim nic. Zobrazim uzivateli hlasku, ze bohuzel na jeho hledani jsme nic nenasli, at zkusi zmenit svuj dotaz. Pripadne neco v tomto smyslu.

**Comment by zabak** [comment]
Ale pozor - já zkoušel texty které jsou i v metadatech - např slunéčko, nebo davidova

**Comment by honza-rychtar** [comment]
@zabak kdyz to zkusis s malym prvnim pismenem, tak to funguje.
@ovyhlidal Vsechny retezece, ktere davas do SOLR dotazu, preved na lowercase. Ne na urovni klavesnice, kde uzivatel pise, ale pri skladani SOLR dotazu.

**Comment by ovyhlidal** [comment]
Opraveno, bude v dalsi verzi
