### ISSUE TITLE
Misto obsahu se zobrazi cerna stranka

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#46]
Misto toho aby se nacetl obsah se zobrazuje cerna obrazovka. 

Pri ziskavani rozliseni pro ctectu se nepodari z xml response ziskat rozliseni a ctecka potom nezobrazi obsah.

**Comment by zabak** [comment]
Jak to u stejných svazků řeší Android?

**Comment by honza-rychtar** [comment]
ImageProperties.xml nemiva spatny format. Myslim, ze tady resite JPEG dokumenty, ktere nemaji Zoomify strukturu a tedy ani ImageProperties.xml.

Bude potreba predelat (mozna uz je) prohlizecku, aby brala i JPEG. Nebo podle typu obrazku (zoomify/jpeg) pouzit ruznou prohlizecku - pro zobrazeni, zoomovani, posouvani JPEGu bude pro iOS urccite nejaka knihovna.

**Comment by ovyhlidal** [comment]
Chapu spravne, ze dle https://github.com/ceskaexpedice/kramerius/wiki/ClientAPIDEV v response na /search/api/v5.0/item/<pid> v datanode je true, tak uzel nese data o obrazku a tim padem nepouziju ctecku, ale prohlizec JPG dokumentu. Je i nejaka jina moznat, jak toto poznat? 
Diky

**Comment by honza-rychtar** [comment]
@ovyhlidal ne, *datanode* by mel byt *true* u vsech modelu *page*, bez ohledu na to, jestli jsou pro obrazek vygenerovane dlazdice.
Poznat by se to dalo tak, ze v *item* neni objekt *zoom* - na to bych ale nespolehal, to je tam nove (nevim presne od ktere verze) a muze se to menit.
Ja to delam tak, ze se zeptam na ImageProperties.xml, napr. http://kramerius.mzk.cz/search/zoomify/uuid:882a8f4f-1dde-4597-802b-77e16c0f68cf/ImageProperties.xml
a pokud neni k dispozici (server vrati 404), tak to znamena, ze pro obrazek neni vygenerovana zoomify struktura a vemu si JPEG - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:882a8f4f-1dde-4597-802b-77e16c0f68cf/streams/IMG_FULL

**Comment by ovyhlidal** [comment]
Ok, super :+1: 
Diky

**Comment by ovyhlidal** [comment]
@honza-rychtar Jak se chova tvoje ctecka v pripade, ze nektere dokumenty maji IMG_Full jen ve formatu djvu?

**Comment by honza-rychtar** [comment]
@ovyhlidal 
v pripade djvu vraci api IMG_FULL stream jako djvu - to jde ale obejit
a) vraci djvu: http://kramerius.mzk.cz/search/api/v5.0/item/uuid:1c0e5c47-435f-11dd-b505-00145e5790ea/streams/IMG_FULL
b) vraci jpeg: http://kramerius.mzk.cz/search/img?pid=uuid:1c0e5c47-435f-11dd-b505-00145e5790ea

Ten img servlet ma nevyhodu, ze ho teoreticky muzou kdykoli zmenit (neni to API).
Vyhodou je, ze vraci vzdy jepg a da se pres nej obrazek scalovat:
http://kramerius.mzk.cz/search/img?pid=uuid:1c0e5c47-435f-11dd-b505-00145e5790ea&stream=IMG_FULL&action=SCALE&scaledHeight=1000
Vrati obrazek v jpeg s vyskou 1000px

Na webu to delam tak, ze se na jpeg (pokud neni zoomify) zeptam pres API a pokud nevrati korektni jpeg (vrati djvu), tak si vemu jpeg pres img servlet.
Takto je to pro djvu trochu pomalejsi, ale pro jpegy je to rychlejsi a spolehlivejsi. 

V Android appce to delame pres img servlet vzdy - at uz je to jpeg nebo djvu, protoze potrebujeme mit moznost scalovani - IMG_FULL muze vratit klidne 8000x8000px, coz Android jako bitmapu nenacte.
Takze berem obrazek s vyskou 1500px
