### ISSUE TITLE
Rozmisteni karet na obrazovce

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#49]
1) Karty jsou na kazde obrazovce rozmisteny jinak - nejnovejsi/doporucene maji dostatecny padding vlevo, vpravo a zadny dole. Obrazova s obsahem sbirky ma nulovy padding ze vsech stran. Obrazovka se seznamem rocniku, cisel periodika ma prehnany horni padding. 

2) Na 8" tabletu se v portrait modu zobrazi karty ve dnou sloupcich, v landscape modu ve 3 sloupcich. Karty maji fixni sirku a konkretne v portrait modu na 8" je mezi kartama strasne velka mezera. 

Layout s karatama by mel byt responzivni a pri jakekoli sirce zarizeni by mela byt mezera mezi kartama stejne velka, menit by se mela sirka karet a pocet sloupcu. Sirka karty by se mela nastavit relativne, napr. 8" portrait: sirka = 50 %, 8" landscape: sirka = 33.333 %. 
Pokud pro zobrazeni karet pouzivas nejaky specializovany grid layout, pak jen nastavit pocet sloupcu a sirku karty nastavit na 100%. 
Kvuli 1) jeste ten grid layout (nebo jine tve reseni) obalit konteinerem, kteremu das nejaky vhodny padding. Tohle pak pouzit na vsech obrazovkach s karatama stejne.

**Comment by ovyhlidal** [comment]
Opraveno
