### ISSUE TITLE
Obsah karet

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#50]
Lepe rozmistit jednotlive polozky na kartach.
1) Ikona typu dokumentu je prilis velka
2) Typu dokumentu je moc blizko horni delici cary a moc daleko odspod. Mel by byt vycentrovany mezi delici carou a spodkem karty
3) Delici cara nad typem dokumentu je moc vyrazna.
4) Nazev dokumentu je vertikalne vycentrovany, coz vede k tomu, ze pokud je nazev jen na jeden radek, tak je moc dole - mel by zacinat stejne vysoko jako v pripade dvouradkoveho.
5) Vetsina dokumentu ma pomer stran thumbnalilu podobny - strana knihy - z toho by se melo vychazet, ted jsou vlevo a vpravo strasne velke mezery u vetsiny dokumentu. Takze zmensit sirku konteineru pro thumbnail a ten pak uvnitr vycentorvat.

Jsou to malickosti, ale proste to bije do oci a nevypada to hezky, resp. mohlo by to vypadat vyrazne lepe.

**Comment by ovyhlidal** [comment]
Opraveno.
