### ISSUE TITLE
Touch feedback

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-ios#51]
Pridat vizualni touch feedback na vsechny interaktivni komponenty - pri tapnuti na komponentu jeste nez zvednu prst by se komponenta mela nejak zvyraznit.
U polozek v menu, tabu a v seznamech (napr. vysledky naseptavace) uz touch feedback je.
Mel by se dodelat jeste u karet (napr. mirne zesednout pozadi), thumbnaily v seznamu stranek, kolecko posuvniku pro vyber stran, ...

**Comment by ovyhlidal** [comment]
Pridam standardni highlight na thumbDown a bude to dustupne od dalsi verze.

**Comment by ovyhlidal** [comment]
Ke standardnim prvkum jsem pridal vizualni feedback.
