### ISSUE TITLE
šířka vyhledávacího pole

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#53]
Zarovnat šířku vyhledávacího pole (včetně tlačítka Cancel) s okrajem karet pod ním.

**Comment by ovyhlidal** [comment]
Chapu to spravne, ze zacatek vyhledavaciho pole umistit stejne daleko od leveho okraje obrazovky jako karty s dokumenty?

**Comment by zabak** [comment]
ano

**Comment by ovyhlidal** [comment]
Opraveno.
