### ISSUE TITLE
V pripade problemu s pripojenim na backend vyvolat chybovou hlasku

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#57]
Pokud spadne kramerius je vhodne zobrazit uzivatele chybovou hlasku. 

@zabak @honza-rychtar Mame nejakou standardizovanou hlasku, ktera se nekde v takovychto pripadech pouziva, abych ji pouzil a tim padem bychom meli konzistentni UI mezi platformami?

Diky

**Comment by zabak** [comment]
Navrhuji Nedaří se navázat spojení s digitální knihovnou MZK - a případně i pod tím tlačítko typu "vybrat jinou knihovnu" které by rozbalilo seznam knihoven. Problém samozřejmě je, že by se muselo k názvu knihovny doplnit ještě skloňování.

**Comment by ovyhlidal** [comment]
V aplikaci aktualne pouzivam standardni systemove dialogy, ktere obsahuji 2 tlacitka. Neni uplne zvykem aby pop up okno po zavreni presmerovalo uzivatele do jine obrazovky. Nejcastejsim pripadem vyskoceni tehle hlasky je podle me to, ze se prerusilo spojeni, takze si myslim, ze by tam mohla byt hlaska zkontrolujte svoje pripojeni pripadne popis toho, ze v menu uzivatel muze zmenit knihovnu.

**Comment by honza-rychtar** [comment]
To ze se nepodarilo navazat spojeni s digitalni knihovnou nepozname. Treba ty vypadky MZK Krameria ted neovlivnuji API, takze to prestane fungovat az pri nacitani obrazku (Hledani, prochazeni, vybrane, nahledy, metadata, ... funguje).
Z toho to ale taky nevyctem. Casto je spatne prave jen nejaky obrazek. 

Vyber jine knihovny po chybe bych vubec neresil (muze byt zpusobene jen chybou jednoho obrazku).

Dulezite je, aby vychozi Kramerius byl stabilni! Pokud nastane chyba v jine nez vychozi knihovne, tak uz uzivatel zdojovou knihovnu jednou zmenil a vi jak na to. Pokud ma vypadek vychozi knihovna, tak je to spatne, protoze uzivatel hned pri prnim setkani s aplikaci narazi na chybu.

To se bohuzel ted deje, Kramerius MZK je v tuhle chvili nejmene stabilnim Krameriem - novi uzivatele Android, iOS a weboveho klienta tak hned narazi na chyby. Navic ten vypadek Krameria MZK ovlivnuje jen obrazky, takze vsichni 3 klienti pusobi, ze funguji, jen se nezobrazi obrazky.

**Comment by zabak** [comment]
Stabilita Krameria MZK je věřím vyřešena, v posledních verzích jsem nenarazil na chování aplikace, které by mi vadilo. Zavírám.
