### ISSUE TITLE
Registr Krameriu

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#60]
Pridat register krameriu do aplikace. 
Pozn. prozatim neni definitivni url

**Comment by honza-rychtar** [comment]
Registr je ted dostupny na subdomene http://registr.digitalniknihovna.cz/
Tohle muzes pouzivat, tam to bude dostupne porad, sice to nebude oficialni url, ani oficialni instalace, ale pokud to budes zkouset tady, tak to bude fungovat dal.

Potom bude registr oficialne nasazevy v openshiftu v MZK a url se zmeni.

**Comment by ovyhlidal** [comment]
Toto je duplikat #9
