### ISSUE TITLE
Useklý název vybrané knihovny v menu

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/kramerius-for-ios#61]
Název vybrané knihovny se nevleze do menu celý. Při kliknutí na knihovnu by mělo pole taky nějak barevně zareagovat, jak to je u jiných prokliků.

**Comment by ovyhlidal** [comment]
Nazev vybrane knihovny jsem uz opravil, ale jeste to neni v soucasne testovaci verzi. Na dalsi testovaci verzi prave pracuju. 
Na graficke zobrazeni kliknuti na polozky uz tu mame issue. 
https://github.com/moravianlibrary/kramerius-for-ios/issues/51

**Comment by ovyhlidal** [comment]
Pri vybirani knihovy a kliknuti na polozku knihovny je zvyrazneni implementovane. Zatim neni implementovane v headru, ktery spousti obrazovku s vyberem knihovny. Otazkou je, zda to ma vubec smysl, kdyz do budoucna stejne vysouvaci menu budemem z aplikace odstranovat.
