### ISSUE TITLE
Aplikace by mela podporovat dokumenty typu "stranka"

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#62]
Pokud prepnu aplikaci na Vedeckou knihovnu v Olomouci, tak na hlavni strance jsou zatim nepodporovane typy dokumentu. 
Jedna se predevsim o model page - http://kramerius.kr-olomoucky.cz/search/api/v5.0/feed/custom

**Comment by ovyhlidal** [comment]
Opraveno

**Comment by honza-rychtar** [comment]
Vybrane dokumenty typu page se pouzivaji jako hack kvuli chybejici moznosti zvolit si nahledovy obrazek dokumentu jiny nez prvni stranka.
Casto byva prvni stranka jen prazdna deska nebo hrbet, takze do vybranych vyberou treba osmou stranku monografie, na ktere je pekny obrazek.
Tohle je jednak nesmysl - nedoporucuju osmou stranku monografi, ale celou monografi. A taky je to jen obchazeni neceho, co se melo davno implementovat. Pridat do Krameria a editoru moznost volby nahledove stranky je prece jednoduche, neni na tom co resit.
@zabak Pohlo se toto nekam?

KNAV to ted taky menila, najednou se mi v klientovi ve vybranych u nich zobrazuje jen jeden dokument misto dvaceti - taky to zmenili na stranky. Kdyz kouknes sem http://kramerius.lib.cas.cz/search/ a rozkliknes si ty monografie na konci, tak zjistis proc. Prvni stranky jsou jen prazdne desky, tak vybrali stranku s nejakym rozumnym obsahem.

V androidim i webovem klientovi to filtruju a stranky zahazuju.
Asi to taky zmenim a vybrane dokumenty typu page zacnu podporovat, ale je potreba rozsirit api/feed/custom - ted z toho v pripade stranky nejde zjistit jestli patri do monografie, mapy, periodika ..... 

Ale jsme zase u toho, ze misto aby se rozsirila funkcionalita Krameria, tak se bude menit API a klienti.

Davalo by smysl do vybranych davat i samostatna cisla periodika - to by se ale taky muselo rozsirit, at mame k dispozici informace pro zobrazeni informaci o periodiku, rocniku, cisle.

@MartinRumanek Bylo by mozne u custom vracet i kontext?
