### ISSUE TITLE
okénko při výpadku připojení - textace tlačítek

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#63]
Při výpadku připojení se objeví okénko s oznámením a pod ním tlačítka "Ano" a "Zrušit". Není ale jasné, co co se má stát, když zvolím jedno nebo druhé.

**Comment by ovyhlidal** [comment]
Ano to je pravda, tak navrhuji prejmenovat Ano na Opakovat. 
Ano - Opakovat? - opakuje pokus o nacteni
Zrusit - prerusi dalsi pokus o nacitani

**Comment by zabak** [comment]
Ještě rozhodnout jestli OK nebo Ano. Aby to bylo v aplikaci konzistentní. Ale nebylo by lapší položit otázku jako Ano/ne? Tj. "Nepodařilo se spojit s digitální knihovnou. Zkusit znovu? Ano/ne"

**Comment by ovyhlidal** [comment]
To je asi nejlepsi. Nahradim hlasku a napisy na tlacitkach.

**Comment by zabak** [comment]
Pro tuto chvíli zavírám, kdyby to bylo nutné upravovat, založí se nové issue.
