### ISSUE TITLE
chování appky na "hotelové" wifi

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#66]
Pokud jsem v hotelu apod, kde pro konektivitu nestačí jen připojení k wifi, ale je nutné se nějak "přihlásit" přes webovou stránku, appka ne vždy rozpozná problém (např. stažení seznamu kolekcí - nic se nezobrazí, ale ani chybová hláška). Chtělo by to hlídat si nějak u všech volání API jestli nedošlo k nečekanému přerušení spojení i v případě, že wifi je dále připojena.

**Comment by ovyhlidal** [comment]
Seznam kolekci pravdepodobne nema implementovanou metodu, ktera oznamuje neuspesne stahnuti. Opravim

**Comment by zabak** [comment]
Jo, vypadalo to tak, že vždycky nejprve vyskočilo okno s chybou. Akorát teda nechápu proč to po tapnutí na dokument hlásí "pozor tato sbírka není veřejně dostupná" a po druhém pokusu o stejný dokument (nebo i jiný) to už funguje. Pokud by sbírka neměla být veřejná, tak není vidět, ne?

**Comment by ovyhlidal** [comment]
Tento bug mi reportovalo vice lidi, zkusim se na to poradne podivat a opravit to.

**Comment by ovyhlidal** [comment]
Toto by melo byt opraveno spolecne s issue ktere bylo spojene s issue v kolekcich... 
Problem byl v tom, ze se spatne rozpasovala informace o dostupnosti (standardne se pouziva policy, ale tady byla dostupnost pod jinym klicem, vlastne je to pomerne zajimave, protoze vsude jinde se pouzivaji anglicke klice, ale tady se pouziva cesky "dostupnost" ... )
