### ISSUE TITLE
Thumbnail dokumentů odkazuje na jiný dokument

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#67]
Jihočeská vědecká knihovna - kolekce regionální mapy - kliknout na nějakou mapu a zobrazí se jiná. Není to v datech.

**Comment by ovyhlidal** [comment]
Toto je bug v parsovani dat, behem dneska by to melo byt vyreseno

**Comment by ovyhlidal** [comment]
Otestovano a vse by melo jiz ukazovat na spravny dokument.
