### ISSUE TITLE
Zoomify ios knihovna

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#68]
Toto vlakno budu udrzovat jako zdroj informaci pro implementaci ios zoomify ctecky. 

@honza-rychtar Chtel jsem se te zeptat, odkud jsi cerpal informace, kdyz jsi psal Android zoomify prohlizecku? 
Diky moc

**Comment by honza-rychtar** [comment]
@ovyhlidal Zoomify prohlizecku pro Android psal @rzeh4n

**Comment by ovyhlidal** [comment]
@honza-rychtar Diky
@rzeh4n Mohl bych se zeptat, odkud jsi cerpal info, kdyz jsi psal ctecku na Android? 
Diky :)

**Comment by rzeh4n** [comment]
Aha, nevšiml jsem si, že se se na mě Honza odkazoval, odpověděl bych dřív.

Na nějakou oficiální dokumentaci jsem nenarazil, prakticky jenom tohle:
http://www.staremapy.cz/zoomify-analyza/
http://www.staremapy.cz/zoomify-analyza/zoomify.py.html

Možná ti pomůže i něco z implementace pro Kramerius pro Android:
https://github.com/moravianlibrary/AndroidZoomifyViewer/tree/master/lib/src/main/java/cz/mzk/tiledimageview/images/zoomify

Když jsem si nebyl něčím jistý, tak jsem občas použil nějakou webovou prohlížečku a díval se přes Chrome DevTools, kdy se tahá která dlaždice. Třeba tady:
http://mapy.mzk.cz/mzk03/001/037/157/2619267319/

Tady je pár příkladů veřejně dostupných zoomify obrázků nejen z mzk, co jsem různě našel. Některé už nefungují:
https://github.com/moravianlibrary/AndroidZoomifyViewer/blob/master/app/src/main/java/cz/mzk/tiledimageview/demonstration/SingleImageExamplesFactory.java

Udělal jsem si backend na Google Appenginu na simulování různých chybové situací:
http://mzk-tiledimageview-demo.appspot.com/

Mám pocit, že nějaký základní popis jsem viděl v nějakém textu od Petra Žabičky snad z roku 2008, ale nějak to nemůžu najít.

Prostě máš:
*  base url
http://mapy.mzk.cz/AA22/0103/ (tady je navíc na ni namapovaná webové prohlížečka)

* ImageProperties.xml
http://mapy.mzk.cz/AA22/0103/ImageProperties.xml
Vždy se to jmenuje přesně _ImageProperties.xml_. Tam jsou všechny potřebné informace o obrázku a struktuře dlaždic.

* samotné obrázky dlaždic
http://mapy.mzk.cz/AA22/0103/TileGroup0/0-0-0.jpg
http://mapy.mzk.cz/AA22/0103/TileGroup0/1-0-0.jpg
http://mapy.mzk.cz/AA22/0103/TileGroup0/1-0-0.jpg
http://mapy.mzk.cz/AA22/0103/TileGroup0/1-0-1.jpg
...

Ještě pozor na na TileGroup. Image server pro Kramerius MZK neřeší TileGroup korektně (i když co je korektně, když není veřejně dostupný standard, že) a přijímá jakékoliv číslo. Např.:
http://kramerius.mzk.cz/search/zoomify/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3/TileGroup0/3-3-2.jpg
ale funguje i:
http://kramerius.mzk.cz/search/zoomify/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3/TileGroup0/3-3-2.jpg
http://kramerius.mzk.cz/search/zoomify/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3/TileGroup1/3-3-2.jpg
http://kramerius.mzk.cz/search/zoomify/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3/TileGroup666/3-3-2.jpg
Na což bych nespoléhal, viz ty ukázky mimo MZK.

**Comment by zabak** [comment]
To nebylo ode mě ale v textu diplomky od Klokana: http://www.staremapy.cz/projekt-diplomka-klokan

**Comment by ovyhlidal** [comment]
Super, diky za info :)

**Comment by zabak** [comment]
Připomínky k chování budoucí prohlížečky: aby se používání gest co nejvíce shodovalo s ibooks. V každém případě v současné verzi chybí náznak že když tapnu na okraj stránky, tak to znamená otoč stránku. Doubletap do stránky=upravit zoom stránky na celou obrazovku. Swipe zprava doleva nebo naopak = otoč stránku.

**Comment by zabak** [comment]
@ovyhlidal myslím, že toto lze zavřít...?

**Comment by ovyhlidal** [comment]
Myslim si, ze toto muzeme zavrit. Delam seznam veci, ktere je treba jeste dodelat a pridavam si na nej double tap to zoom....
