### ISSUE TITLE
Vyber knihovny ma spatny layout

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#7]
Upravit obrazovku s vyberem knihovny - header neni oddeleny od contentu, dlazdice jsou roztahnute pres celou obrazovku a nezapada to vizualne do aplikace.

**Comment by black23** [comment]
Navíc není vůbec jasné, že výběr knihovny proběhle po kliknutí na logo

**Comment by ovyhlidal** [comment]
Nektere visualni chyby jsem odstranil. Zbyva ted vyresit, jakym zpusobem budeme uzivateli signalizovat, ze si prave kliknutim na cele zahlavi muze zmenit knihovnu. Android na to pouziva trojuhelnik v pravem dolnim rohu zahlavi. V iOSu se standardne pouziva sipka v pravo. 
Tady je to hezky videt v nastaveni u music: http://mercury.io/wp-content/uploads/2014/09/chevrons_back_and_music.gif
Navrhuji pouzit stejne chovani i u nas.

**Comment by zabak** [comment]
Souhlasím - chceme, aby uživatel iOS s aplikací pracoval intuitivně jak je zvyklý

**Comment by ovyhlidal** [comment]
Upravil jsem i zalamovani textu a pridal disclosure indicator.
