### ISSUE TITLE
zakázat pootáčení stránky gestem

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#72]
smysl má nanejvýš otáčení po 90 stupních.

**Comment by honza-rychtar** [comment]
Zatim v js prohlizecce by melo stacit pri vytvareni objektu Map toto:
var map = new ol.Map {
    .....
    interactions: ol.interaction.defaults({pinchRotate:false});
    .....
};

**Comment by ovyhlidal** [comment]
Otazkou je, jestli toto bylo v js prohlizecce nebo v prohlizecce, ktera zobrazuje jpgy.

**Comment by zabak** [comment]
Dělá to Když slunéčko svítí, takže předpokládám openlayers.

**Comment by ovyhlidal** [comment]
Opraveno.
