### ISSUE TITLE
Naposled otevřené

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#75]
U naposled otevřených se zobrazí náhledy jen u některých dokumentů - možná to nějak souvisí s tím, že mám naposledy otevřené z několika různých knihoven? Když přepnu knihovnu, tak zůstávají náhledy co tam byly (a nebyly), dokud je neposunu mimo obrazovku, pak se dotáhnou ty ze zvolené knihovny a ostatní zmizí. Navíc jde otevřít jen některé dokumenty (jen monografie?), ostatní nereagují. Většina dokumentů má typ "zvukový nosič" nezávisle na tom co je to za dokument. Když mám vybranou jinou knihovnu než ze které je vybraný naposledy otevřený dokument, tak aplikace spadne po spuštění prohlížečky (měla by se nejprve zvolit příslušná knihovna a to se nestane). Když z naposledy otevřených otevřu autorsky chráněnou věc, zobrazí se prohlížečka stránky, ale stránka se nezobrazí, ani chybová hláška. Teprve po pokusu o otočení stránky se zobrazí upozornění že stránka není veřejně přístupná. Naposledy otevřený dokument se přidává na konec seznamu, měl by být na začátku. Navíc to vypadá, že si aplikace pamatuje jen 20 poprvé otevřených dokumentů, další se nepřidávají).

**Comment by ovyhlidal** [comment]
Tady je problem v tom, ze ukladam naposled otevrene jako dokument, ale neukladam knihovnu, ke ktere patri. To ma za nasledek to, ze pri zmene knihovny se nestahnout spravne obrazky. Ostatni chyby jsou dusledek toho, ze jsem podstatne menil hierarchii aplikace a nektere prechody mezi obrazovkami jsem zapomel upravit. 
Pres vikend vse opravim a  udelam novy build spolecne s upravenym prehravanim hudby.

**Comment by ovyhlidal** [comment]
Pri prepnuti knihovny se uz prepinaji i naposled otevrene dokumenty.
