### ISSUE TITLE
Přehrávač - ovládání z Control Centre

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#76]
Přehrávání by se mělo ovládat z Control centra. Teď když pustím něco na itunes, tak to hraje paralelně s Krameriem a Control Centre o tom neví.

**Comment by zabak** [comment]
Toto pravděpodobně umožní odstranit ikonu Přehrávač z menu...?

**Comment by ovyhlidal** [comment]
Tohle je problem se kterym si hraju uz nejakou dobu a zatim bez vetsich uspechu. Urcite nam to neumozni odstranit ikonu prehravace z menu. Ovladani prehravace z controll centra je jen rozsireni prehavace, takze uzivateli musi byt zachovana moznost ovladat prehravac v aplikaci.

**Comment by ovyhlidal** [comment]
Podarilo se, takze behem vikendu udelam dalsi verzi spolecne s tim, aby se seznam skladeb zobrazoval primo v prehravaci a uzivatel tak bude mit moznost si vybrat skladbu primo z prehravace. Jeste by asi bylo vhodne tam pridat i prohlizeni obrazku, ktere jsou u dane skladby/alba ...
![img_0028](https://cloud.githubusercontent.com/assets/11073775/14382357/7688708c-fd8d-11e5-8e98-0d4642648b24.PNG)

**Comment by ovyhlidal** [comment]
Opraveno
