### ISSUE TITLE
2x po sobě výběr knihovny

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#82]
Pokud jsem v menu výběru knihovny a tapnu znovu na ikonu výběr knihovny, měla by se aplikace vrátit buď na předchozí stránku, nebo na hlavní stránku aktuálně zvolené knihovny. To druhé by možná umožnilo sloučení položek "Knihovna" a "výběr knihovny" - ale nevím jestli je to dobrý nápad. Na telefonu asi ano...?

**Comment by ovyhlidal** [comment]
Dle mych zkusenosti by to bylo pro uzivatele matouci. Vetsi smysl by mozna melo to, ze pokud uzivatel zvoli jinou knihovnu, tak ho to presune do prvniho tabu reprezentujiciho zajimave a vybrane dokumenty knihovny. 

Slouceni tech tabu knihovna a vyber knihovny by nemelo zadny benefit. Stejne by se na obrazovku knihovna muselo pridat nejake tlacitko, ktere by rikalo "tady si muzes prepnout knihovnu", ktere by po kliknuti otevrelo novou obrazovku s vyberem knihovny...

**Comment by zabak** [comment]
Tak jinak - tlačítko "Knihovna" by se nemělo jmenovat "Knihovna" ale "domů", "zpět", "hledat" nebo tak nějak. Tím nebude matoucí. Protože ono se teď stejně nevrací na hlavní stránku, ale když jsem předtím hledal, tak na výsledek hledání. Tj. z mého pohledu to není návrat na začátek, ale fakticky jen o krok zpět.

**Comment by ovyhlidal** [comment]
Knihovnu jsem prejmenoval na Domu, Naposled otevrene na Historie, Vyber knihovny na Knihovna. Pridal jsem zvyrazneni aktualne vybrane knihovny.

**Comment by ovyhlidal** [comment]
@zabak Je treba jeste upravovat tady v tomto issue?

**Comment by zabak** [comment]
Zavírám a v případě potřeby se to znovu otevře v novém issue.
