### ISSUE TITLE
Menu i v prohlížečce stránek?

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#83]
Nemohlo/nemělo by hlavní menu být i v prohlížečce stránek (s tím, že by by zmizelo při přechodu do fullscreenu (tj. když zmizí modré lišty nahoře a dole)?

**Comment by ovyhlidal** [comment]
Osobne si myslim, ze by nemuselo. V okamziku, kdy do aplikace pridam zalozky a to, ze se uzivateli dokument zobrazi na posledni otevrene strance (kde minule ctectku zavrel), tak by to podle me nemelo ani vyznam. Ale jsem otevreny dalsi diskusi.

**Comment by zabak** [comment]
ok zatím zavírám, když na to později narazíme znova, budeme pokračovat v diskusi.
