### ISSUE TITLE
Pridat polozku do nastaveni: Smazat naposled otevrene dokumenty

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#86]

**Comment by zabak** [comment]
Tato položka by měla ale být dostupná skrze systémovou ikonu nastavení, podobně jako jiné budoucí položky nastavení.

**Comment by honza-rychtar** [comment]
Je tato funkcionalita opravdu potrebna?
Proc by tohle uzivatel mel chtit?

**Comment by zabak** [comment]
Záleží na tom, jak dlouhou historii si budu držet. Pokud omezené množštví, tak to není potřeba. Možná by stačilo celkové resetování aplikace do základního nastavení.

**Comment by honza-rychtar** [comment]
I kdyby to bylo neomezene mnozstvi, tak se to usporada od nejnovejsich a uzivatel vidi stale ty NAPOSLEDY otevrene. Nema duvod seznam mazat. Pokud jde o to, ze by bylo naposledy otevrenych dokumentu "strasne" moc, zabiralo by to pamet a zpomalovalo beh aplikace, tak o to se ma starat aplikace a ne uzivatel.

**Comment by ovyhlidal** [comment]
Ok, souhlas. Aplikace se o toto postara sama.
