### ISSUE TITLE
Obrazek by mel pokryvat co nejvetsi cast obrazovky

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#87]
Obecne vsechny obrazky v prohlizecce se musi roztahnout na maximalni moznou velikost. Urcite musi byt zachovan pomer stran pri roztahovani.

**Comment by jandera** [comment]
Toto stale nefunguje, u dokumentů, které se zobrazí větší než display (např.: http://cdk.lib.cas.cz/client/handle/uuid:18a529f9-9839-11e0-bd44-0050569d679d) se po potažení stránky zobrazení zmenší, ale je stále větší než display, tažením lze zobrazit spodní konec stránky, ale horní se vrátí mimo display (i ve čtecím modu - bez modrych lišt). Po provedení výše uvedeného a otočení iPadu na šířku, nelze se stránkou pohybovat vůbec, teprve po přechodu na jinou , další stránku lze se stránkou hýbat. A opět po prvním pohybu dojde ke změně zoomu, tentokrát k mírnému zvětšení. Opět mohu zobrazit dolní konec stránky, ale horní ne a tentokrát celou horní třetinu.

**Comment by zabak** [comment]
Nedokážu reprodukovat. Při přepnutí na KNAV se aplikace chová jako bych byl stále v MZK - tj. bug #151 nesouvisí s hledáním, ale prostě nelze se přepnout do jiné knihovny tak aby to fungovalo. Chtěl jsem otestovat dokument Böhmische Chronik odkázaný výše, protože toto issue je asi vyřešené, ale nemám jak.

**Comment by jandera** [comment]
Ano, mnou popsany problem je odstranen, sice se take nemuzu do KNAV prepnout, ale Böhmische Chronik je u Vas ve sbirce EOD asi na zacatku posledni tretiny.
Ale toto issue "Obrazek by mel pokryvat co nejvetsi cast obrazovky" bych za vyreseny nepokladal, pro zacatek by stacil alespon zamek zoomu, abych pri listovani nemusel kazdou stranku znovu zoomovat a posouvat aby byl text citelny.

**Comment by zabak** [comment]
To už je jiný problém - zámek zoomu, vtvořím na to nové issue
