### ISSUE TITLE
Přehrávač - chování

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#89]
Pustím přehrávač, skladba Clap yo' hands.
Po spuštění se na ose ukáže na konci čas 00:00:02, pak se změní na 00:04:27. Přehrávání ale nezačne.
Tlačítko fast forward zdá se že nefunguje (mačkám asi 3x). Najednou zafunguje se zpožděním. Posuvník je najednou na konci skladby, na začátku osy je čas 00:00:10 a na konci 00:05:57. Vypadá to že první fast forward posune ukazatel na konec osy ale ve skutečnosti jen o 10 s. 
Přesunutím posuvníku ca do 1/3 se na začátku osy vynuluje časový údaj. Logicky, protože ve skutečnosti se posouvá z 10s na 0, akorát je to špatně nastavené na ose.

Pokud během přehrávání vyberu a pustím jinou skladbu, tak se taky rovnou nespustí, nicméně namísto tlačítka play je tlačítko pause, i když to nehraje. Jeho zmáčknutím se spustí přehrávání, pak už se po dalším zmáčknutí skladba zastaví a zobrazí se správně play.

Ačkoli reaguje přehrávání na posun okamžitě, překreslení čsového údaje a posuvníku má nepřijemné zpoždění cca 0,5s.

**Comment by ovyhlidal** [comment]
Toto by jiz melo byt opraveno, ale nemuzu to otestovat, protoze vsechny requesty na hudebni dokumenty vraci prazdne pole....

**Comment by honza-rychtar** [comment]
Zvukove dokumenty obsahuji nahravky - http://www.digitalniknihovna.cz/mzk/search/?sort=newest&accessibility=public&doctypes=soundrecording - krome tech, ktere jsou ve sbirce Zvukove nahravky - http://www.digitalniknihovna.cz/mzk/search/?collections=vc:6b45fd6b-3bbd-4eaf-83fe-2c673497970b (Zlocin a trest 1,2,3)
O te sbirce jsem se bavil s Martinem a rikal mu, at ji radeji smaze, nez aby tam visal poskozena.
Bud neodstranil vsechno, nebo jste tam nekdo zase pridali ty 3 dokumenty (driv jich tam bylo vic).
@LenkaDamborska Smazes tu sbirku? Ono nema smysl, aby tam visela, kdyz nefunguje. Pokud je tam nekde chyba se zvukovymi dokumenty ve sbirkach, tak to testujte na krameriustest a do produkcniho Krameria to dejte az funkcni (Ta nefunkcni sbirka uz je tam 14 dni).

**Comment by zabak** [comment]
Ve vybraných je jiný, fungující zvukový dokument, dá se to na něm testovat. Hlavní problém teď vidím v tom, že se přehrávání nerozjede samo po tapnutí na vybraný dokument, ale musí se ještě dát play.

**Comment by zabak** [comment]
@LenkaDamborska mohli byste obnovit sbírku s volnými zvukovými dokumenty? Předpokládám, že teď už to funguje.

**Comment by zabak** [comment]
Issue vyřešeno, zavírám. Pokud je tam nějaký další bug, bude řešen v novém issue.
