### ISSUE TITLE
Rozsirit interni seznam knihoven 

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius-for-ios#9]
V soucasnosti je mozne vybrat ze 7 knihoven. Je vhodne tento seznam rozsirit.

**Comment by zabak** [comment]
https://registr-krameriu.herokuapp.com/ - prozatímní umístění, ale tady jsou aktuální data. Funguje i https://registr-krameriu.herokuapp.com/libraries/1.json apod.

**Comment by ovyhlidal** [comment]
Da se nejakym zpusobem stahnout i ikona knihovny? 
Seznam knihoven stahnout a rozparsovat neni problem, knihovny vyfiltruju podle verze 5.2.0 a pridam toto do releasu.

**Comment by honza-rychtar** [comment]
JSON se seznamem vsech muzes vzit takto:
https://registr-krameriu.herokuapp.com/libraries.json

Verze 5.2.0 neni nutna, pro Android aplikaci staci verze 5.0.2, takze by mela stacit i pro iOS.
Ale vsechny bych nepridaval. Napr. Narodni muzem nema jediny verejny dokument. Spousta jich nema nastavene vybrane (na to uz bych se vykaslal, kdyz budou az na 10. a dalsim miste ve vyberu).
Taky by bylo dobre mit svoleni knihovny, nebo ji alespon informovat, ze v aplikaci(ch) jeji data zpristupnujeme.
Dal pak logo knihovny - to ale taky neni uplne nutne, ikona se da dohledat.
V Androidi aplikaci mame 8 Krameriu, kde od kazde knihovny mame souhlas, mame od ni zaslanou ikonu, nastavili si verejne vybrane a maji dostatek verejnych dokumentu.
Dalsi 4 knihovny maji zajem o pridani do aplikace: NTK, Karlovy Vary, Filmovy archiv a UK - FSV
Tyto budu ted pridavat do nove verze.

Pokud jde o ikony, tak ty jou v tom registru pevne (jako assety) - url je sice snadardizovane:
https://registr-krameriu.herokuapp.com/assets/logo_KOD_KNIHOVNY.png, ale Rails pridava assetum MD5 v produkci, takze:
https://registr-krameriu.herokuapp.com/assets/logo_[KOD_KNIHOVNY]-[MD5].png
Takze budes muset projit ten seznam https://registr-krameriu.herokuapp.com/
A pro kazdu ikonu budes muset pres kontextove menu - kopirovat URL obrazku.
Napr.:
https://registr-krameriu.herokuapp.com/assets/logo_mkct-bdcfb394c381bea70079d487db043f54e9584f02ee84d9a639398d03facfd975.png
Neni to moc pekne reseni - ten registr zatim neni urcen pro aplikace tretich stran - do budoucna je mozne, ze Android i iOS aplikace bude zdrojove Kramerie brat prave odtud a dynamicky.
Ted si loga stahni a neodkazuj se na ne do registru, url se muze menit.

Ikony jsou v dostatecnem rozliseni.
Ne vsechny ikony jsou oficialni. Nektere jsem si (kvuli weboveho klienta) dohledal a urpavil - nekdy i barvu a pozadi, ....

**Comment by ovyhlidal** [comment]
Super, diky za info :)

**Comment by LenkaDamborska** [comment]
NFA a Karlovy Vary ještě nemají vybrané (psala jsem jim postup, tak snad to bude). UK FSV nastaví Honza H. dnes. 
@honza-rychtar Kdy máš v plánu vydat novou verzi? Napíšu do mail. konference, aby se kdyžtak ozvali další zájemci.

**Comment by honza-rychtar** [comment]
@LenkaDamborska Pristi tyden vydam novou verzi s dalsima knihovnama.
Vybrane uz bych nebral jako podminku, ale upozornujte je na to dal. I kdyz ted pridam Krameria bez vybranych, tak jakmile je nastavi, tak se to v aplikaci projevi hned.
Zmenit to ale tak, ze pokud seznam vybranych je prazdny, tak na hlavni obrazovce sekci s vybranymi schovam a budou tam jen novinky.
@ovyhlidal Na iOS jsou vybrane/novinky jako taby. Slo by tab s vybranymi schovat, pokud je seznam vybranych prazdny? Nebo alespon v tomto pripade defaultne otevrit tab s novinkama?

**Comment by ovyhlidal** [comment]
@honza-rychtar jo je to mozny. Akorat to kdyztak udelam po tom releasu.

**Comment by ovyhlidal** [comment]
@honza-rychtar mam jeden dotaz ohledne toho, co presne rika hodnota u ios ci android...
http://registr.digitalniknihovna.cz/libraries.json
Jsou tam hodnoty 0, 1, 2. Hadam, ze 0 - nedostupna. 2 - dostupna, ale 1?
Diky za odpoved.

**Comment by zabak** [comment]
Mělo by to být navázané na http://registrkrameriu.mzk.cz
Hodnota 1 znamená Ready (tj. technicky vše připraveno). Aplikace by se měla ale řídit hodnotou 2, což znamená, že daný Kramerius má být v aplikaci vidět.

**Comment by ovyhlidal** [comment]
Ok, Diky za info.

**Comment by ovyhlidal** [comment]
@honza-rychtar Jeste bych mel jeden dotaz. Jak je to ted s ikonou knihovny? Uz je mozny ikony stahovat primo z registru, nebo je potreba se je porad manualne stahnout? 
Diky

**Comment by zabak** [comment]
@ovyhlidal kdy bude toto?

**Comment by ovyhlidal** [comment]
Zbyva mi doresit stahovani ikon knihoven. @honza-rychtar jak je to s ikonami knihoven? zmenilo se to, co jsi psal na zacatku? Diky za info.

**Comment by zabak** [comment]
json už vrací i umístění loga, např. pro MZK "logo":"http://registrkrameriu.mzk.cz/libraries/mzk/logo" s tím že URL uvedené v jsonu se pak přesměruje na skutečné umístění loga.

**Comment by ovyhlidal** [comment]
oka diky :)

**Comment by ovyhlidal** [comment]
Registr krameriu je pridan do aplikace. Jeste mam dotaz, ohledne Knihovny Akademie věd ČR. V registru je URL: http://kramerius.lib.cas.cz. Kdyz ji dam do prohlizece, tak se protokol prepne na https, jenze aplikace se porad dotazuje pod http a misto jsonu s daty dostane errorovou hlasku. Jak se toto da vyresit?

**Comment by zabak** [comment]
upravil jsem v registru krameriů záznam KNAV na https, už to korektně funguje. Zavírám.
