### ISSUE TITLE
Přehrávač - po skončení přehrávání skladby spadne celá aplikace

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#90]
Mimo to aplikace spadne i když pustím skladbu, přepnu do jiné knihovny, přepnu zpět do přehrávače a skladbu zastavím a pustím. Možná jde o stejnou chybu, možná o dvě různé.

**Comment by ovyhlidal** [comment]
Co se tyce padani pri prepnuti knihovny - tento problem je v tom, ze prehravac si vzdy pred prehratim skladby zjisti aktualni knihovnu a z ni potom prehrava hudbu... v tomto konkretnim pripade tam hudba neni a nemam tuto vyjimku osetrenou. Do dalsi verze opravim obe chyby.

**Comment by zabak** [comment]
Myslím, že u přehrávače by nevadilo, kdyby hrál dál. Člověk si pustí něco na pozadí a pak dál pracuje. Zatím nemáme playlisty, ale až budou podporované, tak budeme chtít, aby fungovaly i když jsou skladby z různých knihoven.

**Comment by ovyhlidal** [comment]
To je docela dulezity poznatek k tomu, jak se ma prehravac chovat. Zkusim na tom zapracovat pres vikend.

**Comment by zabak** [comment]
Na Androidu je to tak, že při změně knihovny přehrávání okamžitě končí. @honza-rychtar jak to vidíš ty?

**Comment by ovyhlidal** [comment]
Opravil obe kriticke chyby.

**Comment by zabak** [comment]
Neopravil - pokud přepnu do jiné knihovny, tak sice přehrávání skončí, ale pokud pak v menu znovu vyberu přehrávač, tak si pamatuje poslední skladbu (tu z jiné knihovny), jsem schopen ji pustit (pak se chová divoce ukazatel celkové délky skladby) a pak spadne podobně jako předtím, protože jsem v jiné knihovně.

**Comment by ovyhlidal** [comment]
Asi jsem napsal komentar jinam nez jsem puvodne chtel. Kazdopadne opravim co nejdriv.

**Comment by ovyhlidal** [comment]
Opraveno chovani prehravace. K testovani bude ve verzi 1.1.2(10)
