### ISSUE TITLE
Nezobrazují se svazky v pdf

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#92]
Např všechny knihy v kolekci Academia v MZK

**Comment by ovyhlidal** [comment]
Posilam tento request na ktery dostanu prazdnou odpoved. http://kramerius.mzk.cz/search/api/v5.0/search?q=collection:%22vc:98859247-7400-4f29-9312-45cb24e56723%22%20AND%20dostupnost:*public*%20AND%20(fedora.model:monograph%20OR%20fedora.model:periodical%20OR%20fedora.model:graphic%20OR%20fedora.model:archive%20OR%20fedora.model:manuscript%20OR%20fedora.model:map%20OR%20fedora.model:sheetmusic%20OR%20fedora.model:soundrecording)&rows=30

**Comment by zabak** [comment]
@LenkaDamborska předej to prosím někomu.

**Comment by honza-rychtar** [comment]
@ovyhlidal Jasne ze to vraci prazdny vysledek - v tehle sbirce jsou pouze neverejne dokumenty a ty to v tom dotazu filtrujes jen na verejne.

**Comment by ovyhlidal** [comment]
To jsem prehlidl ...

**Comment by zabak** [comment]
@LenkaDamborska máme v Krameriu veřejné pdf?

**Comment by honza-rychtar** [comment]
@zabak 
Jasne, 31 - http://kramerius.mzk.cz/search/api/v5.0/search?fl=PID,dc.title&q=img_full_mime:application/pdf%20AND%20dostupnost:public%20AND%20level:0&rows=50

**Comment by zabak** [comment]
Konkrétně titul Monarchie kouzelné hrací strojky je volný a v pdf, ale nenačte se v pdf prohlížečce ale v normální zoomify prohlížečce, zdá se. Takže není nic vidět.

**Comment by ovyhlidal** [comment]
Opraveno, bude pripraveno k testovani v dalsim buildu aplikace 1.2.0 build 6

**Comment by zabak** [comment]
funguje, zavírám
