### ISSUE TITLE
UX úpravy

### ISSUE THREAD

**Issue by jkdubr** [moravianlibrary/kramerius-for-ios#93]
![img_0759](https://cloud.githubusercontent.com/assets/1224279/14551233/98c7ebbc-02d0-11e6-8949-b89c1d10a870.PNG)
![img_0760](https://cloud.githubusercontent.com/assets/1224279/14551237/98ca89f8-02d0-11e6-9d0b-1b5e3e418f37.PNG)
![img_0763](https://cloud.githubusercontent.com/assets/1224279/14551236/98ca4c36-02d0-11e6-8f88-c4491b02cc2e.PNG)
![img_0765](https://cloud.githubusercontent.com/assets/1224279/14551234/98c87c26-02d0-11e6-997f-557ee6193559.PNG)
![img_0766](https://cloud.githubusercontent.com/assets/1224279/14551235/98c9d0da-02d0-11e6-80ae-26ba89c8448f.PNG)
# # @

**Comment by ovyhlidal** [comment]
Super diky za feedback. 
Ohledne moznosti prohlizeni, potrebujeme vymyslet nejakou jednoznacnou ikonu, ktera jasne uzivateli rekne, ze se jedna o verejny/neverejny dokument/stranku. Android na to pouziva ikonu zamku. 
Neco takoveho: http://ic8.link/2862

**Comment by ovyhlidal** [comment]
@zabak Ohledne prejmenovani tabu:
Budeme tedy mit taby: Knihovna, Kolekce, Historie, Knihovny... Souhlas? Myslim si, ze asi lepsi jednoslovne nazvy nevymyslime.

**Comment by zabak** [comment]
Místo "Knihovna" bych dal něco jako "Obsah" nebo tak... Viz též #82 
To knihovna a knihovny je hodně podobné.

**Comment by zabak** [comment]
Ještě k ikoně informací o dokumentu: ta co je tam teď je tak nevýrazná, že jsem si chvíli myslel že v aplikaci není. Bylo by lepší použít ikonu z aplikace pro Android, nebo obdobnou, výraznější.

**Comment by honza-rychtar** [comment]
Tyhle klasicke ikony by mely byt standardni pro iOS, ne pro Android.
Napr. tady https://icons8.com/web-app/for/all/info - jsou iOS/Android/ .. ikony

**Comment by ovyhlidal** [comment]
Pouzivam ikony z toho co psa Honza, jen musim zvolit jine podbarveni. Pravdepodobne jeste vymenim i modrou barvu na tech hornich i dolnich barech. Dal bych tam nejakou mene vyraznou a prijemnejsi pro oci...

**Comment by zabak** [comment]
mě se zdá že problém je, že ta ikona je moc subtilní. Díky antialiasingu se úplně ztratí. Nebo jen nemá bílou, ale šedou barvu??

**Comment by ovyhlidal** [comment]
Vse krome (ikony i, kterou budu menit spolecne s predelavanim a integraci nove knihovny pro zobrazovani) je hotovo a pripraveno na testovani.

**Comment by ovyhlidal** [comment]
Vsechny graficke issues jsou vyreseny v soucasne testovaci verzi 1.2.0.

**Comment by zabak** [comment]
ano, vyřešeno, zavírám
