### ISSUE TITLE
Kolekce z předchozí knihovny

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/kramerius-for-ios#94]
Pokud mám vybranou kolekci v jedné knihovně, tak se po změně knihovny po tapnutí na kolekce dostanu na poslední vybranou kolekci z předchozí knihovny.

**Comment by ovyhlidal** [comment]
Opraveno - pri zmene knihovny se aplikace nevracela do vychoziho zobrazeni. Nyni uz funguje.
