### ISSUE TITLE
Noviny - nemožnost "čtecího modu"

### ISSUE THREAD

**Issue by jandera** [moravianlibrary/kramerius-for-ios#96]
Při otevření např. Lidových novin nebo Rovnosti (z fondu MZK), kdy se zobrazí stranka větší než display, nelze tapnutím přejít do "čtecího modu" - nezmizí modré lišty. Zoomování se chová také zvláštně, obvzlášť při otočení obrazovky na šířku i při zpětném otočení na výšku. Po vícenásobném zoomování aplikace spadne.

**Comment by ovyhlidal** [comment]
@jandera o jake zarizeni se jednalo?

**Comment by jandera** [comment]
IPad2  iOS 9.3.1

**Comment by ovyhlidal** [comment]
Opravil jsem pad aplikace, pridal jsem cteci mod, pridal jsem moznost otacet stranky prstem pokud jsou dostatecne odzoomovane. Jeste resim problem s tim, ze se da stranka odzoomovat a potom prechod na dalsi stranku je stranka vice zazoomovana.

**Comment by zabak** [comment]
vyřešeno
