### ISSUE TITLE
Hledání - našptávač při přerušeném spojení komplikuje psaní

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#97]
Pokud začnu psát vyhledávací dotaz a zlobí připojení, tak vyskočí okénko, že není spojení, opakovat ano/zrušit. Problém je, že vyskočí-li toto okno, schová se klávesnice, takže po každém znaku musím vyvolávat klávesnici znovu.

**Comment by ovyhlidal** [comment]
Toto je dane tim, ze chybova hlaska se v aplikaci zobrazuje jako modalni vyskakovaci okno a to v okamziku zobrazeni prevezme veskery focus v aplikaci na sebe coz je standardni chovani. To ze okenko vyskakuje vicekrat je dano tim, ze pro kazdy dalsi napsany znak se pokousim poslat request na server a pokud server neodpovida, tak se zobrazuje chybova hlaska. 

Pokud bychom chteli aby se errorova hlaska chovala jinak, tak je to mozne jedine v pripade, ze predelame kompletne graficky navrh zobrazovani chybovych hlasek a vymyslime jiny zpusob, jak uzivateli zobrazovat chybove stavy.

**Comment by zabak** [comment]
nedá se nastavit něco jako že se chybová hláška při zobrazené klávesnici neukáže? Nebo že se neukáže u našeptávače nikdy. Našeptávač není kritická funkce - podstatné je, jestli to něco vyhledá, když se dá Hledat. Pak ale naopak musím zpětnou vazbu mít, jestli nic nenašlo protože není spojení, nebo proto, že se fakt nic nenašlo.

**Comment by honza-rychtar** [comment]
Souhlasim s Petrem, naseptvac neni kriticka funkce. Tohle neni chyba ve smyslu ovlivneni dalsi funkcionality. Je to jen nejaka funkce navic, jejiz docasny vypadek by nemel (nesmi) narusit chovani aplikace a uz vubec nema obtezovat uzivatele modalnim oknem s chybovou hlaskou. 
Predstav si, ze bys to delal treba v pripade, ze se neodesle hit do Google Analytics ...

Predelavat navrh zobrazivani chybovych hlasek neni nutne, jen tohle neber jako chybu, resp. nepredkladej to uzivateli jako chybu. Bud to uplne ignoruj a proste nic nenaseptej, nebo zobraz vhodnou hlasku do naseptavace ("vyhledavam ...", "Zadne vysledky", "Naseptavani se nezdarilo") - tohle nejsou vysledky naseptavace, ale stav naseptavace slouzici jako graficky hint pro uzivatele v dobe, kdyz se nezobrazuji vysledky.

Z uzivatelskeho hlediska je nesmysl, aby pri psani "babicka" naseptavac pri postupnem psani "babi" naseptaval, ve stavu "babic" bude vypadek a uzivateli se zobrazi okno a prerusi ho to v dalsim psani. Pravdepodobne by po napsani dalsiho znaku ve stavu "babick" zase naseptavac funogoval a zobrazil uzivateli navrhy a je mu umplne jedno, ze nekde v mezicase byla chyba v komunikaci.

**Comment by zabak** [comment]
Problém přetrvává i v nové verzi. Tohle je hodně nepříjemné chování.

**Comment by ovyhlidal** [comment]
Toto bych mel opravit behem dneska a bude to soucasti dnesniho releasu.

**Comment by ovyhlidal** [comment]
Bylo by mozne udelate re-test tohoto issue? Diky

**Comment by zabak** [comment]
vyřešeno, zavírám
