### ISSUE TITLE
Hledání - brněnské noviny nejdou najít

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-ios#98]
Pokud hledám Brněnské noviny, tak najdu hafo věcí, ale Brněnské noviny v seznamu nejsou, ani nejde seznamem dále listovat. Dají se najít jedině když napíšu pouze noviny a pak jsou asi dvacáté v pořadí Brněnské noviny.

**Comment by ovyhlidal** [comment]
Tento problem je opraven v soucasnem releasu, ktery se testuje.

**Comment by zabak** [comment]
funguje
